// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenPageLogo_screen_init(void)
{
    ui_ScreenPageLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ScreenPageLogo, 360, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenPageLogo, lv_color_hex(0x0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPageLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
#if USE_GIF_LOGO == 1
    imageLogo = lv_gif_create(ui_ScreenPageLogo);
    lv_gif_set_src(imageLogo, &gifSnake400);
    lv_obj_align(imageLogo, LV_ALIGN_CENTER, 0, 0);
#else
    // SKY GARAGE text logo using Conthrax font
    lv_obj_t *label_sky = lv_label_create(ui_ScreenPageLogo);
    lv_label_set_text(label_sky, "SKY");
    lv_obj_set_style_text_font(label_sky, &ui_font_FontTypoderSize56, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label_sky, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(label_sky, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(label_sky, LV_ALIGN_CENTER, 0, -20);

    lv_obj_t *label_garage = lv_label_create(ui_ScreenPageLogo);
    lv_label_set_text(label_garage, "GARAGE");
    lv_obj_set_style_text_font(label_garage, &ui_font_FontTypoderSize36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label_garage, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(label_garage, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(label_garage, LV_ALIGN_CENTER, 0, 30);

    imageLogo = NULL; // No image logo anymore

    // White border ring (same as Gear page style)
    lv_obj_t *spinnerLogo = lv_spinner_create(ui_ScreenPageLogo, 1000, 90);
    lv_obj_set_width(spinnerLogo, 360);
    lv_obj_set_height(spinnerLogo, 360);
    lv_obj_set_align(spinnerLogo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(spinnerLogo, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_arc_color(spinnerLogo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(spinnerLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(spinnerLogo, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(spinnerLogo, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(spinnerLogo, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(spinnerLogo, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
#endif
    lv_obj_add_event_cb(ui_ScreenPageLogo, ui_event_logo_background, LV_EVENT_ALL, NULL);
}

