// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
// UI主题命名为 PINK_CAT(粉色猫咪)，主色调为粉色，副色调为紫色
#include "ui.h"
#include "ui_helpers.h"
#include "ui_ext.h"
#include "ui_disp_item.h"
#include "app_obd_dsp/app_event.h"
#include <driver/gpio.h>
#include "bsp_obd_dsp/bsp_board.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "bsp_obd_dsp/lcd_driver/ST77916.h"
#include "bsp_obd_dsp/elm327_ble_client.h"
#include "bsp_obd_dsp/espnow_link.h"
#include "app_obd_dsp/vehicle_profiles.h"
#include "app_obd_dsp/boot_block_player.h"
#include "app_obd_dsp/boot_media_mount.h"
#include "esp_system.h"
#include "esp_random.h"
#include "esp_log.h"
#include "esp_idf_version.h"
#include "esp_timer.h"
#include <stdio.h>


static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t * ui_ScreenPageLogo;
lv_obj_t * imageLogo;
lv_obj_t * imageEasterEgg;

// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
lv_obj_t * ui_ScreenPageMain;
lv_obj_t * ui_ImageMainPageback;
lv_obj_t * ui_SpinnerMainPage;
lv_obj_t * ui_ArcGearNumBack;
lv_obj_t * ui_LabelGeningRpmText;
lv_obj_t * ui_LabelGeningRpmUnitText;
lv_obj_t * ui_LabelCarSpeedText;
lv_obj_t * ui_LabelCarSpeedUnitText;
lv_obj_t * ui_ContainerMainPageBottomBlock;
lv_obj_t * ui_LabelGearNumText;
lv_obj_t * ui_ContainerMainPageMlieageBlock;
lv_obj_t * ui_LabelMainMlieageText;
lv_obj_t * ui_LabelMainMieageNum;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageGear
void ui_ScreenPageGear_screen_init(void);
lv_obj_t * ui_ScreenPageGear;
lv_obj_t * ui_SpinnerGearPage;
lv_obj_t * ui_GearPageArcGearNumBack;
lv_obj_t * ui_GearPageArcLabelGearNumText;
lv_obj_t * ui_ImageGearBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageRpm
void ui_ScreenPageRpm_screen_init(void);
lv_obj_t * ui_ScreenPageRpm;
lv_obj_t * ui_SpinnerRpmPage;
lv_obj_t * ui_RpmPageArcRpmBack;
lv_obj_t * ui_RpmPageArcLabelRpmText;
lv_obj_t * ui_RpmPageArcLabelRpmUnit;
lv_obj_t * ui_ImageRpmBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageSpeed
void ui_ScreenPageSpeed_screen_init(void);
lv_obj_t * ui_ScreenPageSpeed;
lv_obj_t * ui_SpinnerSpeedPage;
lv_obj_t * ui_SpeedPageArcSpeedBack;
lv_obj_t * ui_SpeedPageArcLabelSpeedText;
lv_obj_t * ui_SpeedPageArcLabelSpeedUnit;
lv_obj_t * ui_ImageSpeedBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageEasterEgg
void ui_ScreenPageEasterEgg_screen_init(void);
lv_obj_t * ui_ScreenPageEasterEgg;
lv_obj_t * ui_SpinnerEasterEgg;
lv_obj_t * ArcPageEasterEggBack;
lv_obj_t * ui_ImageEggBlackEar;
lv_obj_t * ui_LabelEasterEggInfo;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageBLEScan
void ui_ScreenPageBLEScan_screen_init(void);
lv_obj_t * ui_ScreenPageBLEScan;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageTemp
void ui_ScreenPageTemp_screen_init(void);
lv_obj_t * ui_ScreenPageTemp;

// SCREEN: ui_ScreenPageTempCustom
void ui_ScreenPageTempCustom_screen_init(void);
lv_obj_t * ui_ScreenPageTempCustom;

// SCREEN: ui_ScreenPageOilPressure
void ui_ScreenPageOilPressure_screen_init(void);
lv_obj_t * ui_ScreenPageOilPressure;

// SCREEN: ui_ScreenPageInfo
void ui_ScreenPageInfo_screen_init(void);
extern lv_obj_t * ui_ScreenPageInfo;

// SCREEN: ui_ScreenPageInfoCustom
void ui_ScreenPageInfoCustom_screen_init(void);
lv_obj_t * ui_ScreenPageInfoCustom;
// labels defined in ui_ScreenPageInfo.c
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageSettings
void ui_ScreenPageSettings_screen_init(void);
lv_obj_t * ui_ScreenPageSettings;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageOilWarn
void ui_ScreenPageOilWarn_screen_init(void);
lv_obj_t * ui_ScreenPageOilWarn;
void ui_ScreenPageRpmWarn_screen_init(void);
lv_obj_t * ui_ScreenPageRpmWarn;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageNeedle (指针式可配置仪表)
void ui_ScreenPageNeedle_screen_init(void);
lv_obj_t * ui_ScreenPageNeedle;
lv_meter_scale_t * ui_NeedleScale;
lv_meter_indicator_t * ui_NeedleIndic;
lv_obj_t * ui_NeedleMeter;
lv_obj_t * ui_NeedleValueLabel;
lv_obj_t * ui_NeedleNameLabel;
lv_obj_t * ui_NeedleUnitLabel;
// SCREEN: ui_ScreenPageNeedleConfig
void ui_ScreenPageNeedleConfig_screen_init(void);
lv_obj_t * ui_ScreenPageNeedleConfig;

// SCREEN: ui_ScreenPageMultiGauge (三连表设置: 主/从 + 选主表)
void ui_ScreenPageMultiGauge_screen_init(void);
lv_obj_t * ui_ScreenPageMultiGauge;

// SCREEN: ui_ScreenPageChartConfig (曲线数据源选择)
void ui_ScreenPageChartConfig_screen_init(void);
lv_obj_t * ui_ScreenPageChartConfig;

// SCREEN: ui_ScreenPageChartAlarm (曲线报警阈值设置)
void ui_ScreenPageChartAlarm_screen_init(void);
lv_obj_t * ui_ScreenPageChartAlarm;

// SCREEN: ui_ScreenPageIntro (三连表开机动画 RACE/AS/ONE)
void ui_ScreenPageIntro_screen_init(void);
lv_obj_t * ui_ScreenPageIntro;

// SCREEN: ui_ScreenPageODBProtocal
void ui_ScreenPageODBProtocal_screen_init(void);
lv_obj_t * ui_ScreenPageODBProtocal;
lv_obj_t * ui_SpinnerODBProtocalEgg;
lv_obj_t * ui_ArcPageODBProtocalBack;
lv_obj_t * ui_RollerODBProtocalChoose;
lv_obj_t * ui_ImageODBProtocalBlackEar;
lv_obj_t * ui_LabelOBDIIText;
lv_obj_t * ui_LabelSureTipText;

// EVENTS
lv_obj_t * ui____initial_actions0;


static uint16_t usSaveProtTimeCnt = 0; //OBD协议保存计时

// IMAGES AND IMAGE SETS
#define SAVE_PROTOCOL_TIME 2000 //保存协议长按时间ms
 
///////////////////// TEST LVGL SETTINGS ////////////////////
/* ---- Gauge sweep (刷表) animation ----
   数字从最小递增到最大(约1s) → 顶点保持(0.5s) → 背光闪一下(最高0.2s→最低0.2s),
   闪完的同一拍恢复设定亮度并切回真实数值。扫表全程背光维持最低(SWEEP_BL_MIN)。
   背光由 sweep_step 导出, 主从表据同一 step 得到同一亮度 → 三连表闪光同步。 */
#define SWEEP_RPM_PEAK   8000   // 刷表最高转速
#define SWEEP_SPEED_PEAK 999    // 刷表最高车速
#define SWEEP_TICK_MS    40     // 扫表期间刷新周期(高刷让数字平滑递增)
#define SWEEP_STEPS_UP   25     // 25×40ms ≈ 1s 从最小递增到最大
#define SWEEP_STEPS_HOLD 13     // 13×40ms ≈ 0.5s 在最大值保持
#define SWEEP_STEPS_FLASH 5     // 5×40ms ≈ 0.2s 每段闪光时长(高段/低段各一段)
#define SWEEP_BL_MIN     3      // 扫表期间 & 闪光低段的背光(%), 可调
#define SWEEP_BL_MAX     100    // 闪光高段背光(%)
#define SWEEP_TOTAL      (SWEEP_STEPS_UP + SWEEP_STEPS_HOLD + 2*SWEEP_STEPS_FLASH)
#define OIL_PRESS_TREND_POINTS 30
#define OIL_PRESS_TREND_SAMPLE_MS 1000
// 扫表进度仅在 LVGL 任务内推进; 主表 espnow TX 任务通过 ui_sweep_get_step() 只读广播。
// 取值 0=关闭, 1~SWEEP_TOTAL=动画中。showroom 广播值(200+)由 espnow_link 自行编码, 不再复用此变量。
static volatile int  s_sweep_step = 0;
static int  s_sweep_bl_last = -1;       // 扫表期间已下发的背光(%), -1=非扫表态; 用于变化时才写LEDC及结束时恢复设定亮度
static bool s_sweep_pending = false;    // BLE 在 Logo 期间连上，Logo 消失后再触发
static bool s_prev_ble_connected = false;

/* ---- 数字递增动画阈值 (供 disp_item_update 使用) ---- */
#define ANIM_THRESH_RPM   50   // 转速差值 ≤50 逐 ±1
#define ANIM_THRESH_SPD   10   // 车速差值 ≤10 逐 ±1
#define ANIM_THRESH_TEMP   5   // 温度差值 ≤5 逐 ±1

// 自适应步进: 差值 ≤ threshold 逐 ±1, 差值 > threshold 按比例快速逼近
// RPM/Speed 页面需要同时更新 label + arc，逻辑与 disp_item_update 不同，故保留局部副本
static inline int32_t anim_step_i32(int32_t displayed, int32_t target, int32_t threshold)
{
    int32_t diff = target - displayed;
    if (diff == 0) return displayed;
    int32_t abs_diff = (diff > 0) ? diff : -diff;
    int32_t step = (diff > 0) ? 1 : -1;

    if (abs_diff > threshold) {
        int32_t rapid = abs_diff / 3;     // 每拍吃掉 ~33% 差距
        if (rapid < 2) rapid = 2;          // 最小 2 步
        if (rapid > abs_diff) rapid = abs_diff;
        step = (diff > 0) ? rapid : -rapid;
    }
    return displayed + step;
}

// 转速报警测试模式
volatile int s_rpm_flash_test_ticks = 0;
void ui_rpm_flash_test_start(void) { s_rpm_flash_test_ticks = 60; }  // ~2s 测试闪烁

// LVGL 任务句柄(由 app_main 设置), 闪烁期间临时提优先级独占 CPU
TaskHandle_t g_lvgl_task_handle = NULL;

// ===== Showroom 模式 =====
// 极简设计: 每表独立跑固定时序循环, 不依赖 ESP-NOW 逐页同步
// 进入 showroom 时各表用 esp_random() 选 4 个随机数据页, 之后本地定时切页
static volatile bool s_showroom_active = false;
static uint8_t s_showroom_tap_cnt = 0;
static uint32_t s_showroom_last_tap_ms = 0;
#define SHOWROOM_TAP_TIMEOUT_MS  1500
#define SHOWROOM_TAP_NEED        10
#define SHOWROOM_SLOT_COUNT      8
#define SHOWROOM_DATA_PAGES      4   // 随机数据页数量

// 固定循环: Logo → 动画 → rand0 → Needle → rand1 → Chart → rand2 → rand3
// 每 slot 的 tick 数 (1 tick = 100ms), 0 = 等动画播完
static const uint8_t s_showroom_slot_ticks[SHOWROOM_SLOT_COUNT] = {
    20,  // 0: Logo 2s
    0,   // 1: 动画 (等播完)
    30,  // 2: random[0] 3s
    30,  // 3: Needle 3s
    30,  // 4: random[1] 3s
    30,  // 5: Chart 3s
    30,  // 6: random[2] 3s
    30,  // 7: random[3] 3s
};
static uint8_t  s_showroom_slot = 0;
static uint16_t s_showroom_tick = 0;
static uint8_t  s_showroom_rand_pages[SHOWROOM_DATA_PAGES];  // 启动时随机选好
static lv_obj_t *s_showroom_video_scr = NULL;

// 开机/视频状态 (前移, showroom_load_slot 需要)
static volatile int s_intro_step = 0;
static int64_t s_boot_start_us = 0;
static int64_t s_intro_start_us = 0;
static bool    s_intro_shown = false;
static volatile bool s_boot_video_active = false;
static volatile bool s_boot_video_done = false;
static volatile bool s_boot_video_ready = false;
static int64_t s_boot_video_start_us = 0;
static lv_obj_t *s_boot_video_screen = NULL;
static lv_timer_t *s_boot_video_timer = NULL;

// slot → 页面索引
static uint8_t showroom_slot_to_page(uint8_t slot)
{
    switch (slot) {
        case 0: return 1;  // Logo
        case 1: {          // 动画: 根据设置
            uint8_t ie = nvs_intro_enable_get();
            return (ie >= 2) ? 0 : (ie == 1) ? 2 : 3;
        }
        case 3: return 8;  // Needle
        case 5: return 9;  // Chart
        default: {         // 随机数据页
            uint8_t ri = (slot == 2) ? 0 : (slot == 4) ? 1 : (slot == 6) ? 2 : 3;
            return s_showroom_rand_pages[ri];
        }
    }
}

static void showroom_load_slot(uint8_t slot)
{
    uint8_t page = showroom_slot_to_page(slot);
    if (page == 0) {
        // Video 页
        if (s_boot_video_ready || s_boot_video_active) return;  // 已加载
        uint8_t iv = nvs_intro_enable_get();
        const char *pfx = (iv == 3) ? "b" : (iv == 4) ? "c" : "a";
        char mp[64], dp[64];
        snprintf(mp, sizeof(mp), "/bootmedia/%s_block.txt", pfx);
        snprintf(dp, sizeof(dp), "/bootmedia/%s_block.bin", pfx);
        boot_block_player_set_paths(mp, dp);
        if (boot_media_mount()) {
            if (s_showroom_video_scr) { lv_obj_del(s_showroom_video_scr); s_showroom_video_scr = NULL; }
            s_showroom_video_scr = lv_obj_create(NULL);
            lv_obj_set_style_bg_color(s_showroom_video_scr, lv_color_black(), LV_PART_MAIN);
            lv_obj_set_style_bg_opa(s_showroom_video_scr, 255, LV_PART_MAIN);
            lv_obj_set_style_border_width(s_showroom_video_scr, 0, LV_PART_MAIN);
            lv_obj_set_style_radius(s_showroom_video_scr, 360, LV_PART_MAIN);
            lv_obj_clear_flag(s_showroom_video_scr, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_t *canvas = NULL;
            if (boot_block_player_create(s_showroom_video_scr, &canvas)) {
                s_boot_video_ready = true;
            } else {
                lv_obj_del(s_showroom_video_scr);
                s_showroom_video_scr = NULL;
            }
        }
    } else if (page == 2) {
        // RACE/AS/ONE: 直接启动动画
        s_intro_step = 1;
        s_intro_shown = false;
        s_intro_start_us = esp_timer_get_time();
        if (ui_ScreenPageIntro == NULL) ui_ScreenPageIntro_screen_init();
        lv_scr_load_anim(ui_ScreenPageIntro, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, false);
    } else {
        // 普通页面
        static const struct { lv_obj_t **scr; void (*init)(void); } pages[] = {
            { NULL, NULL },  // 0 unused
            { &ui_ScreenPageLogo,       ui_ScreenPageLogo_screen_init },
            { NULL, NULL },  // 2 handled above
            { &ui_ScreenPageGear,       ui_ScreenPageGear_screen_init },
            { &ui_ScreenPageRpm,        ui_ScreenPageRpm_screen_init },
            { &ui_ScreenPageSpeed,      ui_ScreenPageSpeed_screen_init },
            { &ui_ScreenPageTemp,       ui_ScreenPageTemp_screen_init },
            { &ui_ScreenPageInfo,       ui_ScreenPageInfo_screen_init },
            { &ui_ScreenPageNeedle,     ui_ScreenPageNeedle_screen_init },
            { &ui_ScreenPageOilPressure,ui_ScreenPageOilPressure_screen_init },
        };
        if (page < 10 && pages[page].init) {
            if (*pages[page].scr == NULL) pages[page].init();
            lv_scr_load_anim(*pages[page].scr, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, false);
        }
    }
}

// 视频同步信号 (复用 intro_step, 值 >5 不触发 RACE/AS/ONE 渲染)
#define VIDEO_SYNC_READY  250
#define VIDEO_SYNC_PLAY   251

// 前向声明
static void boot_enter_default_page(void);

// 视频专用高频 timer (33ms ≈ 30fps)
static void boot_video_timer_cb(lv_timer_t *t)
{
    if (!s_boot_video_active) return;
    int64_t now_us = esp_timer_get_time();
    uint32_t elapsed_ms = (uint32_t)((now_us - s_boot_video_start_us) / 1000);
    boot_block_player_update(elapsed_ms);
    if (boot_block_player_is_finished()) {
        ESP_LOGI(TAG, "Boot video finished");
        s_boot_video_active = false;
        s_boot_video_ready = false;
        boot_block_player_destroy();
        if (s_boot_video_timer) { lv_timer_del(s_boot_video_timer); s_boot_video_timer = NULL; }

        if (s_showroom_active) {
            // showroom 模式: 不跳页, 保持最后一帧, 等轮播自动切走
            boot_media_unmount();
        } else {
            // 正常开机: 直接进默认页
            s_boot_video_done = true;
            boot_enter_default_page();
            boot_media_unmount();
            // boot_enter_default_page 内 lv_scr_load_anim(..., true) 已设 auto_del,
            // LVGL 会在过渡动画结束后自动释放旧屏幕, 此处不能手动 lv_obj_del,
            // 否则动画期间访问已释放对象导致 crash (LoadProhibited).
            s_boot_video_screen = NULL;
        }
    }
}

// 前向声明
static void showroom_handle_tap(void);
void ui_showroom_set_active(bool en);
void ui_showroom_set_page_from_sync(int sweep_step);

// 主表 espnow TX 任务只读广播扫表进度; 从表不再回写(扫表由 OBD 缓存值自然跟随)。
int  ui_sweep_get_step(void) { return s_sweep_step; }

bool ui_showroom_is_active(void) { return s_showroom_active; }

void ui_showroom_set_active(bool en) {
    s_showroom_active = en;
    s_showroom_tap_cnt = 0;
    if (en) {
        ESP_LOGI("showroom", "ENTER role=%d", nvs_cfg_get()->device_role);
        s_sweep_step = 0;
        // 随机选 4 个数据页, 用 position 偏移保证三表各不同
        static const uint8_t pool[] = { 3, 4, 5, 6, 7 };
        uint8_t pos = nvs_device_position_get();
        if (pos < 1 || pos > 3) pos = 1;
        for (int i = 0; i < SHOWROOM_DATA_PAGES; i++)
            s_showroom_rand_pages[i] = pool[(i * 3 + pos - 1) % 5];
        // 从 slot 0 开始
        s_showroom_slot = 0;
        s_showroom_tick = 0;
        showroom_load_slot(0);
    } else {
        ESP_LOGI("showroom", "EXIT");
    }
}

// 从表: 收到主表信号后进入 showroom 或跟随 slot。
// 仅 LVGL 任务读写 (espnow recv 经 app_event 队列, 在 my_timerMain 内调用), 无需 volatile。
static int s_showroom_pending_slot = -1;  // -1=无, 0-7=跟随slot
static bool s_showroom_pending_enter = false;

void ui_showroom_set_page_from_sync(int sweep_step) {
    if (sweep_step >= 200 && sweep_step < 210) {
        // 跟随主表 slot
        s_showroom_pending_slot = sweep_step - 200;
        if (!s_showroom_active) {
            s_showroom_pending_slot = -1;
            s_showroom_pending_enter = true;
            s_sweep_step = 0;
        }
    } else if (sweep_step >= 100 && sweep_step < 200 && !s_showroom_active) {
        s_showroom_pending_enter = true;
        s_sweep_step = 0;
    }
}

// 点击计数(版本页/任意页共用)
static void showroom_handle_tap(void) {
    if (s_showroom_active) return;  // 已进入, 不再响应
    uint32_t now = lv_tick_get();
    if (now - s_showroom_last_tap_ms > SHOWROOM_TAP_TIMEOUT_MS) s_showroom_tap_cnt = 0;
    s_showroom_last_tap_ms = now;
    s_showroom_tap_cnt++;
    if (s_showroom_tap_cnt >= SHOWROOM_TAP_NEED) {
        s_showroom_tap_cnt = 0;
        ui_showroom_set_active(true);  // 只进不退, 断电重启退出
    }
}

// 假数据生成(随机游走)
static void showroom_fake_data(void) {
    static float fake_rpm = 2500, fake_spd = 60, fake_clt = 90, fake_oil = 95;
    static float fake_iat = 35, fake_load = 65, fake_tps = 40, fake_boost = 5;
    fake_rpm  += ((float)(esp_random() % 200) - 100) * 2;  if (fake_rpm < 800) fake_rpm = 800; if (fake_rpm > 7500) fake_rpm = 7500;
    fake_spd  += ((float)(esp_random() % 20) - 10) * 0.5f; if (fake_spd < 0) fake_spd = 0; if (fake_spd > 200) fake_spd = 200;
    fake_clt  += ((float)(esp_random() % 4) - 2) * 0.1f;   if (fake_clt < 80) fake_clt = 80; if (fake_clt > 105) fake_clt = 105;
    fake_oil  += ((float)(esp_random() % 6) - 3) * 0.2f;   if (fake_oil < 80) fake_oil = 80; if (fake_oil > 130) fake_oil = 130;
    fake_iat  += ((float)(esp_random() % 4) - 2) * 0.1f;   if (fake_iat < 20) fake_iat = 20; if (fake_iat > 50) fake_iat = 50;
    fake_load += ((float)(esp_random() % 20) - 10);         if (fake_load < 10) fake_load = 10; if (fake_load > 100) fake_load = 100;
    fake_tps  += ((float)(esp_random() % 16) - 8);          if (fake_tps < 0) fake_tps = 0; if (fake_tps > 100) fake_tps = 100;
    fake_boost+= ((float)(esp_random() % 10) - 5) * 0.1f;  if (fake_boost < -5) fake_boost = -5; if (fake_boost > 20) fake_boost = 20;
    obd_data_set_rpm((uint16_t)fake_rpm);
    obd_data_set_speed((uint8_t)fake_spd);
    obd_data_set_coolant_temp((int16_t)fake_clt);
    obd_data_set_oil_temp((int16_t)fake_oil);
    obd_data_set_intake_temp((int16_t)fake_iat);
    obd_data_set_load_pct((int16_t)fake_load);
    obd_data_set_tps((int16_t)fake_tps);
    obd_data_set_boost_x10((int16_t)(fake_boost * 10));
    obd_data_set_oil_pressure_x10((int16_t)(30 + (esp_random() % 40)));
    obd_data_set_brake_temp_x10((int16_t)(200 + (esp_random() % 300)));
}

// 三连表开机动画同步: 主表按时间线驱动 s_intro_step 并广播; 从表由 espnow recv 写入跟随。
//   0=未开始/仍在logo, 1=TC, 2=+-, 3=+OFF, 4=全显示(保持), 255=完成→进页面
int  ui_intro_get_step(void) { return s_intro_step; }
void ui_intro_set_step(int step) {
    // Showroom 模式下各表自驱动 intro 动画, 不接受主表覆盖
    if (s_showroom_active) return;
    s_intro_step = step;
}
static int16_t s_oil_pressure_trend[OIL_PRESS_TREND_POINTS];
static bool s_oil_pressure_trend_ready = false;
static uint32_t s_oil_pressure_trend_tick = 0;
// 通用曲线页: 无效样本哨兵(区别于合法负值如水温-10) + 当前数据项的原始值量程(刷新时钳位/设Y轴)
// CHART_INVALID 已迁移到 ui_disp_item.h
static int32_t s_chart_ymin = 0;
static int32_t s_chart_ymax = 100;

// disp_item 系统已迁移到 ui_disp_item.c/h

static uint8_t needle_active_source(void)
{
    uint8_t src = nvs_cfg_get()->needle_source_idx;
    if (src >= DISP_ITEM_COUNT) src = DISP_ITEM_CLT;
    return src;
}

void ui_needle_apply_source(void)
{
    if (!ui_NeedleMeter || !ui_NeedleScale) return;
    uint8_t src = needle_active_source();
    const needle_scale_meta_t *ns = &s_needle_scale_meta[src];
    // 270° 扫角，起始角 135°（开口朝下居中），与经典机械仪表一致
    lv_meter_set_scale_range(ui_NeedleMeter, ui_NeedleScale, ns->nmin, ns->nmax, 270, 135);
    lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, ns->nmin);
    if (ui_NeedleNameLabel) lv_label_set_text(ui_NeedleNameLabel, s_disp_meta[src].name);
    if (ui_NeedleUnitLabel) lv_label_set_text(ui_NeedleUnitLabel, s_disp_meta[src].unit);
}

void ui_needle_page_update(float sweep_ratio, int16_t clt, int16_t iat, int16_t oil,
                           int16_t load_pct, int16_t tps, int32_t bat_mv,
                           int16_t oilp_x10, int16_t brake_x10,
                           uint16_t rpm, uint16_t speed, int16_t boost_x10)
{
    if (!ui_ScreenPageNeedle || !ui_NeedleMeter || !ui_NeedleIndic) return;
    uint8_t src = needle_active_source();
    const needle_scale_meta_t *ns = &s_needle_scale_meta[src];

    // 连接成功后的刷表自检：指针 nmin→nmax→nmin 全程扫动
    if (sweep_ratio >= 0.0f) {
        if (sweep_ratio > 1.0f) sweep_ratio = 1.0f;
        int32_t nval = ns->nmin + (int32_t)((float)(ns->nmax - ns->nmin) * sweep_ratio);
        lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, nval);
        disp_item_set_text(ui_NeedleValueLabel, src, nval * ns->div, true);
        return;
    }

    int32_t raw = 0;
    bool valid = disp_item_read_value(src, clt, iat, oil, load_pct, tps, bat_mv,
                                      oilp_x10, brake_x10, rpm, speed, boost_x10, &raw);

    static int32_t s_disp_needle = 0;
    static uint8_t s_last_needle_src = 0xFF;
    if (s_last_needle_src != src) {
        s_last_needle_src = src;
        s_disp_needle = 0;  // 切源时清零, 避免从旧源值爬升
    }
    /* 阈值按量程 3%: 小量程(温度)逐±1平滑, 大量程(RPM)按比例快速逼近 */
    int32_t needle_thresh = (ns->nmax - ns->nmin) / 30;
    if (needle_thresh < 2) needle_thresh = 2;

    disp_item_update(&s_disp_needle, ui_NeedleValueLabel, src, raw, valid, needle_thresh);

    // 指针位置: 用平滑后的值
    int32_t nval = (s_disp_needle / ns->div);
    if (nval < ns->nmin) nval = ns->nmin;
    if (nval > ns->nmax) nval = ns->nmax;
    lv_meter_set_indicator_value(ui_NeedleMeter, ui_NeedleIndic, nval);
}

static void oil_pressure_trend_init(void)
{
    if (s_oil_pressure_trend_ready) return;

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS; ++i) {
        s_oil_pressure_trend[i] = CHART_INVALID;
    }

    s_oil_pressure_trend_ready = true;
}

static void oil_pressure_trend_push(int16_t sample_x10)
{
    oil_pressure_trend_init();

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS - 1; ++i) {
        s_oil_pressure_trend[i] = s_oil_pressure_trend[i + 1];
    }
    s_oil_pressure_trend[OIL_PRESS_TREND_POINTS - 1] = sample_x10;
}

// 通用曲线刷新: Y 量程 = s_chart_ymin..s_chart_ymax(由 ui_chart_apply_source 按数据项设),
// 无效样本(CHART_INVALID)保持上一个有效值; 支持合法负值(如水温)。
static void oil_pressure_chart_refresh(void)
{
    if (!ui_ChartOilPressure || !ui_OilPressureChartSeries) return;

    int32_t last_valid = s_chart_ymin;
    bool has_last = false;

    lv_chart_set_range(ui_ChartOilPressure, LV_CHART_AXIS_PRIMARY_Y, s_chart_ymin, s_chart_ymax);

    for (uint32_t i = 0; i < OIL_PRESS_TREND_POINTS; ++i) {
        int16_t sample = s_oil_pressure_trend[i];
        int32_t v;

        if (sample != CHART_INVALID) {
            last_valid = sample;
            has_last = true;
        }

        v = has_last ? last_valid : s_chart_ymin;
        if (v < s_chart_ymin) v = s_chart_ymin;
        if (v > s_chart_ymax) v = s_chart_ymax;

        lv_chart_set_value_by_id(ui_ChartOilPressure, ui_OilPressureChartSeries, i, v);
    }

    lv_chart_refresh(ui_ChartOilPressure);
}

// 按 chart_source_idx 应用曲线页的标题/圆点/单位/颜色/Y量程(数据源变化后调用)
void ui_chart_apply_source(void)
{
    uint8_t src = nvs_cfg_get()->chart_source_idx;
    if (src >= DISP_ITEM_COUNT) src = DISP_ITEM_OILP;
    const disp_item_meta_t *m = &s_disp_meta[src];
    const needle_scale_meta_t *ns = &s_needle_scale_meta[src];
    s_chart_ymin = ns->nmin * ns->div;   // 原始值量程(与喂入曲线的原始值一致)
    s_chart_ymax = ns->nmax * ns->div;
    if (ui_LabelChartTitle) {
        lv_label_set_text(ui_LabelChartTitle, m->name);
        lv_obj_set_style_text_color(ui_LabelChartTitle, lv_color_hex(m->color), LV_PART_MAIN);
    }
    if (ui_ChartDot) lv_obj_set_style_bg_color(ui_ChartDot, lv_color_hex(m->color), LV_PART_MAIN);
    if (ui_LabelChartUnit) lv_label_set_text(ui_LabelChartUnit, m->unit);
    if (ui_ChartOilPressure) {
        lv_obj_set_style_line_color(ui_ChartOilPressure, lv_color_hex(m->color), LV_PART_ITEMS);
        // 折线实际用 series 自己的颜色(会覆盖 ITEMS 样式), 必须直接改 series 颜色才会变色
        if (ui_OilPressureChartSeries) ui_OilPressureChartSeries->color = lv_color_hex(m->color);
        lv_chart_set_range(ui_ChartOilPressure, LV_CHART_AXIS_PRIMARY_Y, s_chart_ymin, s_chart_ymax);
        lv_chart_refresh(ui_ChartOilPressure);
    }
    // 重置趋势缓冲, 避免切换数据源后残留旧曲线
    s_oil_pressure_trend_ready = false;
    s_oil_pressure_trend_tick = 0;
}

// ===== 开机流程状态 =====
static bool    s_boot_done = false;

// 开机结束进入默认页(Logo 超时 或 开机动画完成后调用)
static void boot_enter_default_page(void)
{
    const nvs_user_cfg_t *pg_cfg = nvs_cfg_get();

    // 首次刷机无保存设备: 直接进 BLE 扫描页让用户手动选
    if (pg_cfg->ble_device_name[0] == '\0') {
        if (ui_ScreenPageBLEScan == NULL) ui_ScreenPageBLEScan_screen_init();
        lv_scr_load_anim(ui_ScreenPageBLEScan, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, true);
        ui_ScreenPageLogo = NULL;
        imageLogo = NULL;
        s_boot_done = true;
        return;
    }

    lv_obj_t **target_scr = NULL;
    void (*target_init)(void) = NULL;
    // 默认页: 0=Temp,1=Info,2=Chart,3=Needle,4=Gear,5=Rpm,6=Speed
    switch(pg_cfg->default_page) {
        case 0: target_scr = &ui_ScreenPageTemp;  target_init = ui_ScreenPageTemp_screen_init;  break;
        case 1: target_scr = &ui_ScreenPageInfo;  target_init = ui_ScreenPageInfo_screen_init;  break;
        case 2: target_scr = &ui_ScreenPageOilPressure; target_init = ui_ScreenPageOilPressure_screen_init;  break;
        case 3: target_scr = &ui_ScreenPageNeedle; target_init = ui_ScreenPageNeedle_screen_init;  break;
        case 4: target_scr = &ui_ScreenPageGear;  target_init = ui_ScreenPageGear_screen_init;  break;
        case 5: target_scr = &ui_ScreenPageRpm;   target_init = ui_ScreenPageRpm_screen_init;   break;
        case 6: target_scr = &ui_ScreenPageSpeed; target_init = ui_ScreenPageSpeed_screen_init; break;
        default: target_scr = &ui_ScreenPageTemp; target_init = ui_ScreenPageTemp_screen_init;  break;
    }
    if(*target_scr == NULL) target_init();
    lv_scr_load_anim(*target_scr, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, true);
    ui_ScreenPageLogo = NULL;
    imageLogo = NULL;
    s_boot_done = true;
    if(s_sweep_pending) { s_sweep_pending = false; s_sweep_step = 1; }  // 开机动画期间连上的刷表挂起, 全部播完进默认页此刻触发
}

void my_timerMain(lv_timer_t * timer)
{
    // ---- 处理事件队列 (ESP-NOW / BLE 跨 task 事件) ----
    {
        app_event_t evt;
        while (app_event_recv(&evt)) {
            switch (evt.type) {
                case APP_EVT_ESPNOW_SYNC_SLOT:
                    ui_showroom_set_page_from_sync((int)evt.data.u8);
                    break;
                case APP_EVT_ESPNOW_INTRO_STEP:
                    ui_intro_set_step((int)evt.data.u8);
                    break;
                case APP_EVT_ESPNOW_ENTER_SHOWROOM:
                    ui_showroom_set_active(true);
                    break;
                default:
                    break;
            }
        }
    }

    static uint16_t usRpm = 0;
    static uint16_t ucSpeed = 0;  // uint16_t 以支持刷表时的999
    static enGear eGear = GEAR_NEUTRAL;
    static bool s_rpm_flash_red = false;  // 转速报警闪烁状态(函数级, 供自适应刷新读取)
    // 刷表动画判定(排除 showroom 同步值 200+)
    #define IN_SWEEP (s_sweep_step > 0 && s_sweep_step <= SWEEP_TOTAL)
    static uint8_t ucOnlyOnce = 0;
    static uint32_t ulOpenLightTimeCnt = 0;

    /* ---- 一次性读取 OBD 数据，供温度页和 Info 页共用 ---- */
    int16_t clt      = obd_data_get_coolant_temp();
    int16_t iat      = obd_data_get_intake_temp();
    int16_t oil      = obd_data_get_oil_temp();      // 真实机油温度 °C (SSM 22 10 17), -100=无效
    int16_t oilp_x10 = obd_data_get_oil_pressure_x10(); // 机油压力 0.1bar, -1=无效
    int16_t brake_x10 = obd_data_get_brake_temp_x10(); // 刹车温度 0.1°C
    int16_t load_pct = obd_data_get_load_pct();      // 发动机负荷 0~100%, -1=无效
    int16_t tps      = obd_data_get_tps();
    int32_t bat_mv   = obd_data_get_bat_mv();
    int16_t boost_x10 = obd_data_get_boost_x10(); // 涡轮表压 0.1bar, -32768=无效
    const nvs_user_cfg_t *user_cfg = nvs_cfg_get();

    /* ---- 触发刷表 ----
       主表: ELM327 蓝牙连上瞬间触发并自行推进动画;
       从表: 不自触发, 由主表广播的 sweep_step 同步驱动(espnow recv → app_event 队列)。 */
    bool is_slave = (nvs_cfg_get()->device_role == ESPNOW_ROLE_SLAVE);
    // "已连接"信号: 从表=收到主表数据, 主表=ELM327蓝牙已连(供状态显示与主表扫表触发共用)
    bool ble_now = is_slave ? espnow_link_slave_has_data() : elm327_ble_is_connected();
    if(!is_slave) {
        if(ble_now && !s_prev_ble_connected) {
            if(s_boot_done) {
                s_sweep_step = 1;       // 开机动画(Logo/SKY GAUGE/RACE AS ONE)已全部播完，立即刷表
            } else {
                s_sweep_pending = true; // 开机动画还在播，先挂起，进默认页那刻再触发
            }
        }
        s_prev_ble_connected = ble_now;
    }

    /* ---- Showroom 模式: 主表驱动 slot, 从表跟随 ---- */
    // 从表: 进入 showroom
    if (!s_showroom_active && s_showroom_pending_enter) {
        s_showroom_pending_enter = false;
        s_boot_done = true;
        ui_showroom_set_active(true);
    }
    // 从表: 跟随主表 slot
    if (s_showroom_active && is_slave && s_showroom_pending_slot >= 0) {
        uint8_t new_slot = (uint8_t)s_showroom_pending_slot;
        s_showroom_pending_slot = -1;
        if (new_slot != s_showroom_slot) {
            // 清理当前 slot
            uint8_t old_page = showroom_slot_to_page(s_showroom_slot);
            if (old_page == 0 && s_boot_video_active) {
                s_boot_video_active = false; s_boot_video_ready = false;
                boot_block_player_destroy(); boot_media_unmount();
                if (s_boot_video_timer) { lv_timer_del(s_boot_video_timer); s_boot_video_timer = NULL; }
            }
            if (old_page == 2) { s_intro_step = 0; s_intro_shown = false; }
            // 跳到主表的 slot
            s_showroom_slot = new_slot;
            s_showroom_tick = 0;
            showroom_load_slot(s_showroom_slot);
        }
    }
    if (s_showroom_active && !IN_SWEEP) {
        if (!is_slave) showroom_fake_data();

        // 动画 slot: 视频准备好后自动开始播放 (主从都执行)
        uint8_t cur_page = showroom_slot_to_page(s_showroom_slot);
        if (s_showroom_slot == 1 && cur_page == 0 && s_boot_video_ready && !s_boot_video_active) {
            lv_scr_load(s_showroom_video_scr);
            s_boot_video_active = true;
            s_boot_video_start_us = esp_timer_get_time();
            if (!s_boot_video_timer)
                s_boot_video_timer = lv_timer_create(boot_video_timer_cb, 33, NULL);
        }

        // 本地 tick 切页:
        //   主表: 所有 slot 都跑
        //   从表: 仅 Logo(0) 和动画(1) 跑本地 tick (保证同步切动画)
        //         其余 slot 纯跟主表广播 (避免闪现)
        bool should_tick = !is_slave || s_showroom_slot <= 1;
        if (should_tick) {
            bool anim_playing = (cur_page == 0 && s_boot_video_active) ||
                                (cur_page == 2 && s_intro_step > 0 && s_intro_step < 255);
            if (!anim_playing) {
                s_showroom_tick++;
            }
            uint8_t max_t = s_showroom_slot_ticks[s_showroom_slot];
            if (max_t == 0) {
                max_t = anim_playing ? 255 : 1;
            }
            if (s_showroom_tick >= max_t) {
                // 离开当前 slot 时清理
                if (cur_page == 0 && s_boot_video_active) {
                    s_boot_video_active = false;
                    s_boot_video_ready = false;
                    boot_block_player_destroy();
                    boot_media_unmount();
                    if (s_boot_video_timer) { lv_timer_del(s_boot_video_timer); s_boot_video_timer = NULL; }
                }
                if (cur_page == 2) { s_intro_step = 0; s_intro_shown = false; }
                s_showroom_slot = (s_showroom_slot + 1) % SHOWROOM_SLOT_COUNT;
                s_showroom_tick = 0;
                showroom_load_slot(s_showroom_slot);
            }
        }
        // 主表广播当前 slot (从表用于纠偏)
        if (!is_slave) s_sweep_step = 200 + s_showroom_slot;
    }

    /* ---- 数据来源：刷表 or 真实 OBD ---- */
    float sweep_ratio = -1.0f;   // <0 = 非刷表(实时数据)
    if(IN_SWEEP) {
        int step = s_sweep_step;
        float ratio;
        if(step <= SWEEP_STEPS_UP) {
            ratio = (float)step / (float)SWEEP_STEPS_UP;    // 0→1 递增
        } else {
            ratio = 1.0f;   // 保持最大值(hold 阶段)
        }
        sweep_ratio = ratio;
        usRpm   = (uint16_t)(SWEEP_RPM_PEAK * ratio);
        ucSpeed = (uint16_t)(SWEEP_SPEED_PEAK * ratio); // uint16_t 以支持999
        eGear   = (enGear)((int)(6.0f * ratio + 0.5f)); // 最高6档

        /* 背光: 扫表+顶点保持=最低; 到顶后闪一下(高0.2s→低0.2s)。仅在亮度变化那一拍写LEDC。 */
        int bl;
        if      (step <= SWEEP_STEPS_UP + SWEEP_STEPS_HOLD)                     bl = SWEEP_BL_MIN; // 递增+保持
        else if (step <= SWEEP_STEPS_UP + SWEEP_STEPS_HOLD + SWEEP_STEPS_FLASH) bl = SWEEP_BL_MAX; // 闪光高段
        else                                                                   bl = SWEEP_BL_MIN; // 闪光低段
        if(bl != s_sweep_bl_last) { Set_Backlight(bl); s_sweep_bl_last = bl; }

        if(!is_slave) {   // 主表自行推进; 从表的 step 由主表广播设置, 不自增(保持同步)
            s_sweep_step++;
            if(s_sweep_step > SWEEP_TOTAL) s_sweep_step = 0; // 动画结束
        }
    } else {
        /* 扫表刚结束(主/从表皆在 step→0 这一拍): 恢复设定亮度, 与"切回真实数值"同时发生, 只做一次 */
        if(s_sweep_bl_last >= 0) {
            uint8_t d = nvs_cfg_get()->brightness_day;
            if(d < 10) d = 100;   // 0/未配置 → 100, 与开机置背光一致
            Set_Backlight(d);
            s_sweep_bl_last = -1;
        }
        usRpm   = obd_data_get_rpm();
        ucSpeed = obd_data_get_speed();
        eGear   = calculate_gear(usRpm, ucSpeed);
    }
    /*档位页面*/
    {
        static const char *pGearNum[] = {"N","1","2","3","4","5","6","7","8"};
        static enGear s_last_gear_disp = GEAR_NEUTRAL;
        enGear g = (eGear <= GEAR_8) ? eGear : GEAR_8;
        uint8_t gc = vehicle_profile_get_active()->gear_count;
        if (gc < 1) gc = 6;
        if (g != s_last_gear_disp || IN_SWEEP) {
            s_last_gear_disp = g;
            lv_label_set_text(ui_GearPageArcLabelGearNumText, pGearNum[g]);
            lv_arc_set_value(ui_GearPageArcGearNumBack, (uint16_t)g * 100 / gc);
        }
    }
    /*转速页面*/
    {
        static int32_t s_disp_rpm = 0;
        static int32_t s_last_rpm = -1;
        if (IN_SWEEP) { s_disp_rpm = usRpm; }
        else { s_disp_rpm = anim_step_i32(s_disp_rpm, (int32_t)usRpm, ANIM_THRESH_RPM); }
        if (s_disp_rpm != s_last_rpm) {
            s_last_rpm = s_disp_rpm;
            lv_label_set_text_fmt(ui_RpmPageArcLabelRpmText, "%d", (int)s_disp_rpm);
            lv_arc_set_value(ui_RpmPageArcRpmBack, (uint32_t)s_disp_rpm*100/SWEEP_RPM_PEAK);
        }
    }
    /*速度页面*/
    {
        static int32_t s_disp_spd = 0;
        static int32_t s_last_spd = -1;
        if (IN_SWEEP) { s_disp_spd = ucSpeed; }
        else { s_disp_spd = anim_step_i32(s_disp_spd, (int32_t)ucSpeed, ANIM_THRESH_SPD); }
        if (s_disp_spd != s_last_spd) {
            s_last_spd = s_disp_spd;
            lv_label_set_text_fmt(ui_SpeedPageArcLabelSpeedText, "%d", (int)s_disp_spd);
            lv_arc_set_value(ui_SpeedPageArcSpeedBack, (uint32_t)s_disp_spd*100/SWEEP_SPEED_PEAK);
        }
    }

 /*指针页 (可配置数据源, 刷表时同步扫表)*/
    ui_needle_page_update(sweep_ratio, clt, iat, oil, load_pct, tps, bat_mv,
                          oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10);

 /*温度页面*/
    if(ui_LabelTempValue[0]) {
        if(IN_SWEEP) {
            int step = s_sweep_step - 1; // already incremented
            float r;
            if(step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // 保持最大值(hold 阶段)

            for (int i = 0; i < 3; ++i) {
                disp_item_t item = (disp_item_t)(user_cfg->temp_display_map[i] % DISP_ITEM_COUNT);
                lv_label_set_text(ui_LabelTempName[i], s_disp_meta[item].name);
                lv_label_set_text(ui_LabelTempUnit[i], s_disp_meta[item].unit);
                lv_obj_set_style_text_color(ui_LabelTempName[i], lv_color_hex(s_disp_meta[item].color), LV_PART_MAIN);
                if (ui_LabelTempDot[i]) lv_obj_set_style_bg_color(ui_LabelTempDot[i], lv_color_hex(s_disp_meta[item].color), LV_PART_MAIN);

                int32_t sw = disp_item_sweep_value(item, r);
                disp_item_set_text(ui_LabelTempValue[i], item, sw, true);
                disp_item_set_value_color(ui_LabelTempValue[i], item, sw, true);
            }
        } else {
            static int32_t s_disp_temp[3] = {0};
            static uint8_t s_last_temp_map[3] = {0xFF, 0xFF, 0xFF};
            for (int i = 0; i < 3; ++i) {
                disp_item_t item = (disp_item_t)(user_cfg->temp_display_map[i] % DISP_ITEM_COUNT);
                if (s_last_temp_map[i] != user_cfg->temp_display_map[i]) {
                    s_last_temp_map[i] = user_cfg->temp_display_map[i];
                    s_disp_temp[i] = 0;  // 切源时清零, 避免从旧源值爬升
                    lv_label_set_text(ui_LabelTempName[i], s_disp_meta[item].name);
                    lv_label_set_text(ui_LabelTempUnit[i], s_disp_meta[item].unit);
                    lv_obj_set_style_text_color(ui_LabelTempName[i], lv_color_hex(s_disp_meta[item].color), LV_PART_MAIN);
                    if (ui_LabelTempDot[i]) lv_obj_set_style_bg_color(ui_LabelTempDot[i], lv_color_hex(s_disp_meta[item].color), LV_PART_MAIN);
                }

                int32_t value = 0;
                bool valid = disp_item_read_value(item, clt, iat, oil, load_pct, tps, bat_mv, oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, &value);
                disp_item_update(&s_disp_temp[i], ui_LabelTempValue[i], item, value, valid, ANIM_THRESH_TEMP);
            }
        }
    }

    /* 通用曲线页更新: 显示的数据项由 chart_source_idx 决定(合并了原油压/刹车温两页) */
    if (ui_LabelOilPressureText) {
        static int32_t s_disp_chart = 0;
        static uint8_t s_last_chart_src = 0xFF;
        disp_item_t citem = (disp_item_t)(user_cfg->chart_source_idx % DISP_ITEM_COUNT);
        if (s_last_chart_src != user_cfg->chart_source_idx) {
            s_last_chart_src = user_cfg->chart_source_idx;
            s_disp_chart = 0;  // 切源时清零, 避免从旧源值爬升
        }
        int32_t cval = 0;
        bool cvalid;
        if (IN_SWEEP) {
            int step = s_sweep_step - 1;
            float r;
            if (step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // 保持最大值(hold 阶段)
            cval = disp_item_sweep_value(citem, r);
            cvalid = true;
            s_disp_chart = cval;
            disp_item_set_text(ui_LabelOilPressureText, citem, s_disp_chart, cvalid);
            disp_item_set_value_color(ui_LabelOilPressureText, citem, s_disp_chart, cvalid);
        } else {
            cvalid = disp_item_read_value(citem, clt, iat, oil, load_pct, tps, bat_mv,
                                          oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, &cval);
            disp_item_update(&s_disp_chart, ui_LabelOilPressureText, citem, cval, cvalid, ANIM_THRESH_TEMP);
        }

        // 仅非扫表时喂曲线并刷新: 开机扫表动画那一下曲线保持不动(扫表是给指针/数字用的, 趋势图不参与)
        if (!IN_SWEEP) {
            uint32_t now = lv_tick_get();
            if (s_oil_pressure_trend_tick == 0) {
                oil_pressure_trend_init();
                s_oil_pressure_trend_tick = now;
            }
            while ((now - s_oil_pressure_trend_tick) >= OIL_PRESS_TREND_SAMPLE_MS) {
                oil_pressure_trend_push(cvalid ? (int16_t)s_disp_chart : CHART_INVALID);
                s_oil_pressure_trend_tick += OIL_PRESS_TREND_SAMPLE_MS;
            }
            oil_pressure_chart_refresh();
        }
    }

    /* Info 页更新 */
    if (ui_LabelInfoValue[0]) {
        if (IN_SWEEP) {
            int step = s_sweep_step - 1; // already incremented above
            float r;
            if (step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = 1.0f;   // 保持最大值(hold 阶段)

            for (int i = 0; i < 5; ++i) {
                disp_item_t item = (disp_item_t)(user_cfg->info_display_map[i] % DISP_ITEM_COUNT);
                lv_label_set_text(ui_LabelInfoName[i], s_disp_meta[item].name);
                lv_label_set_text(ui_LabelInfoUnit[i], s_disp_meta[item].unit);
                lv_obj_set_style_text_color(ui_LabelInfoName[i], lv_color_hex(s_disp_meta[item].color), LV_PART_MAIN);

                int32_t sw = disp_item_sweep_value(item, r);
                disp_item_set_text(ui_LabelInfoValue[i], item, sw, true);
                disp_item_set_value_color(ui_LabelInfoValue[i], item, sw, true);
            }
        } else {
            static int32_t s_disp_info[5] = {0};
            static uint8_t s_last_info_map[5] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
            for (int i = 0; i < 5; ++i) {
                disp_item_t item = (disp_item_t)(user_cfg->info_display_map[i] % DISP_ITEM_COUNT);
                if (s_last_info_map[i] != user_cfg->info_display_map[i]) {
                    s_last_info_map[i] = user_cfg->info_display_map[i];
                    s_disp_info[i] = 0;  // 切源时清零, 避免从旧源值爬升
                    lv_label_set_text(ui_LabelInfoName[i], s_disp_meta[item].name);
                    lv_label_set_text(ui_LabelInfoUnit[i], s_disp_meta[item].unit);
                    lv_obj_set_style_text_color(ui_LabelInfoName[i], lv_color_hex(s_disp_meta[item].color), LV_PART_MAIN);
                }

                int32_t value = 0;
                bool valid = disp_item_read_value(item, clt, iat, oil, load_pct, tps, bat_mv, oilp_x10, brake_x10, usRpm, ucSpeed, boost_x10, &value);
                disp_item_update(&s_disp_info[i], ui_LabelInfoValue[i], item, value, valid, ANIM_THRESH_TEMP);
            }
        }
    }

    /* 动态更新 EasterEgg(版本页)信息: 加 MODE 行, 并按主/从显示 BLE 或 主表链路 */
    if(ui_LabelEasterEggInfo) {
        const char *mode_str = is_slave ? "SLAVE" : "MASTER";
        const char *conn_label, *conn_name;
        if (is_slave) {
            const char *mname = espnow_link_get_master_name();
            conn_label = "SLAVE";
            conn_name  = (ble_now && mname[0]) ? mname : "--";
        } else {
            const char *dev_name = elm327_ble_get_connected_name();
            if(!dev_name || dev_name[0] == '\0') dev_name = "Not set";
            conn_label = "BLE";
            conn_name  = dev_name;
        }
        lv_label_set_text_fmt(ui_LabelEasterEggInfo,
            "ESP32-S3  IDF %d.%d.%d\n"
            "LVGL %d.%d.%d\n"
            "MODE: %s\n"
            "%s: %s\n"
            "Status: %s",
            ESP_IDF_VERSION_MAJOR, ESP_IDF_VERSION_MINOR, ESP_IDF_VERSION_PATCH,
            LVGL_VERSION_MAJOR, LVGL_VERSION_MINOR, LVGL_VERSION_PATCH,
            mode_str, conn_label, conn_name,
            ble_now ? (is_slave ? "Linked" : "Connected")
                    : (is_slave ? "Waiting" : "Disconnected"));
    }
 
#if EXAMPLE_PIN_NUM_BK_LIGHT >= 0
        //等待500ms后开背光，避免没有初始化完成就开背光，只执行一次
        if(ucOnlyOnce == 0)
        {
            ulOpenLightTimeCnt++;
            if(ulOpenLightTimeCnt > 400 / 200)
            {
                const nvs_user_cfg_t *bl_cfg = nvs_cfg_get();
                uint8_t bright = bl_cfg->brightness_day;
                if(bright < 10) bright = 100;
                Set_Backlight(bright);
                ESP_LOGI(TAG, "Set LCD backlight to %d%%", bright);
                ulOpenLightTimeCnt = 0;
                ucOnlyOnce = 1;//只执行一次
            }
        }
#endif

    /* 底部信息栏(TRIP/ODO/MAX/AVG/TIME)原属已删除的 Main 页面，随之移除。
       里程统计仍由后台任务持续累计，可在其它页面或后续重新接入展示。 */

    /* ===== 视频开机模式 (INTRO >= 2: REI/SHINJI/ASUKA) ===== */
    {
        uint8_t intro_val = nvs_intro_enable_get();
        bool want_video = (intro_val >= 2 && intro_val <= 4);
        if (!s_boot_done && !s_showroom_active && !s_boot_video_done && want_video) {
            const nvs_user_cfg_t *cfg_vm = nvs_cfg_get();
            // Logo 先显示 1 秒, 再进入视频
            static int64_t s_video_logo_start_us = 0;
            if (s_video_logo_start_us == 0) s_video_logo_start_us = esp_timer_get_time();
            int64_t logo_el_ms = (esp_timer_get_time() - s_video_logo_start_us) / 1000;
            if (logo_el_ms < 1000) return;  // Logo 展示中, 跳过
            // 阶段1: 准备视频 (根据 intro_val 选文件)
            if (!s_boot_video_ready && !s_boot_video_active && s_boot_video_screen == NULL) {
                // 设置文件路径: 2=a, 3=b, 4=c
                const char *prefix = (intro_val == 3) ? "b" : (intro_val == 4) ? "c" : "a";
                char manifest_path[64], data_path[64];
                snprintf(manifest_path, sizeof(manifest_path), "/bootmedia/%s_block.txt", prefix);
                snprintf(data_path, sizeof(data_path), "/bootmedia/%s_block.bin", prefix);
                boot_block_player_set_paths(manifest_path, data_path);

                if (boot_media_mount()) {
                    s_boot_video_screen = lv_obj_create(NULL);
                    lv_obj_set_style_bg_color(s_boot_video_screen, lv_color_black(), LV_PART_MAIN);
                    lv_obj_set_style_bg_opa(s_boot_video_screen, 255, LV_PART_MAIN);
                    lv_obj_set_style_border_width(s_boot_video_screen, 0, LV_PART_MAIN);
                    lv_obj_set_style_radius(s_boot_video_screen, 360, LV_PART_MAIN);
                    lv_obj_clear_flag(s_boot_video_screen, LV_OBJ_FLAG_SCROLLABLE);
                    lv_obj_t *canvas = NULL;
                    if (boot_block_player_create(s_boot_video_screen, &canvas)) {
                        // 不 lv_scr_load, 保持 Logo 屏, 等开播时再切
                        s_boot_video_ready = true;
                        ESP_LOGI(TAG, "Boot video ready (logo kept)");
                    } else {
                        lv_obj_del(s_boot_video_screen);
                        s_boot_video_screen = NULL;
                        s_boot_video_done = true;
                    }
                } else {
                    s_boot_video_done = true;
                }
            }
            // 阶段2: 等待同步信号后播放
            if (s_boot_video_ready && !s_boot_video_active) {
                bool should_start = false;
                uint8_t role = cfg_vm->device_role;
                if (role == ESPNOW_ROLE_STANDALONE) {
                    // 单机: 直接播
                    should_start = true;
                } else if (role == ESPNOW_ROLE_MASTER) {
                    // 主表: 广播 READY → 等从表上线 → 等 800ms 准备 → 广播 PLAY + 自己播
                    // 超时 5s 无从表也直接播
                    static int64_t s_master_ready_us = 0;
                    static bool s_master_slaves_seen = false;
                    if (s_master_ready_us == 0) {
                        s_master_ready_us = esp_timer_get_time();
                        s_intro_step = VIDEO_SYNC_READY;
                    }
                    if (!s_master_slaves_seen && espnow_master_online_slaves() > 0) {
                        s_master_slaves_seen = true;
                        s_master_ready_us = esp_timer_get_time();  // 重置计时, 从此刻等 800ms
                    }
                    int64_t wait_ms = (esp_timer_get_time() - s_master_ready_us) / 1000;
                    if ((s_master_slaves_seen && wait_ms >= 800) || wait_ms > 5000) {
                        s_intro_step = VIDEO_SYNC_PLAY;
                        should_start = true;
                        s_master_ready_us = 0;
                        s_master_slaves_seen = false;
                    }
                } else {
                    // 从表: 等收到 PLAY 信号, 超时 5s 兜底
                    static int64_t s_slave_wait_us = 0;
                    if (s_slave_wait_us == 0) s_slave_wait_us = esp_timer_get_time();
                    int64_t wait_ms = (esp_timer_get_time() - s_slave_wait_us) / 1000;
                    int intro = ui_intro_get_step();
                    if (intro >= VIDEO_SYNC_PLAY || wait_ms > 5000) {
                        should_start = true;
                        s_slave_wait_us = 0;
                    }
                }
                if (should_start) {
                    lv_scr_load(s_boot_video_screen);  // 此刻才切屏, Logo 保持到最后一刻
                    s_boot_video_active = true;
                    s_boot_video_start_us = esp_timer_get_time();
                    s_boot_video_timer = lv_timer_create(boot_video_timer_cb, 33, NULL);
                    ESP_LOGI(TAG, "Boot video started");
                }
            }
            if (s_boot_video_active || s_boot_video_ready) return;
        }
    } // end video mode scope

    /* ===== 开机流程 / Showroom Intro 回放 ===== */
    bool run_intro = (!s_boot_done && !s_showroom_active) ||
                     (s_showroom_active && showroom_slot_to_page(s_showroom_slot) == 2);
    if (run_intro)
    {
        int64_t now_us = esp_timer_get_time();
        if (s_boot_start_us == 0) s_boot_start_us = now_us;
        int64_t boot_el = now_us - s_boot_start_us;
        bool intro_en = nvs_intro_enable_get();
        bool in_showroom_intro = s_showroom_active && showroom_slot_to_page(s_showroom_slot) == 2;

        if (!is_slave || in_showroom_intro) {
            if (s_intro_step == 0) {
                if (in_showroom_intro || (intro_en == 1 && espnow_master_online_slaves() > 0)) {
                    s_intro_start_us = now_us;
                    s_intro_step = 1;
                } else if ((intro_en != 1 && boot_el > 1000000) ||
                           (intro_en == 1 && boot_el > 3000000)) {
                    s_intro_step = 255;
                }
            } else if (s_intro_step != 255) {
                int64_t el = now_us - s_intro_start_us;
                s_intro_step = (el < 500000) ? 1 : (el < 1000000) ? 2 : (el < 1500000) ? 3
                             : (el < 2000000) ? 4 : (el < 3000000) ? 5 : 255;
            }
        } else {
            // 从表: 等主表同步信号, 5s 超时才跳默认页
            if (s_intro_step == 0) {
                if (boot_el > 5000000) s_intro_step = 255;
            }
        }

        // 渲染 + 屏幕切换
        if (s_intro_step >= 1 && s_intro_step <= 5) {
            if (!s_intro_shown) {
                if (ui_ScreenPageIntro == NULL) ui_ScreenPageIntro_screen_init();
                if (!in_showroom_intro) {
                    lv_scr_load_anim(ui_ScreenPageIntro, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, false);
                    ui_ScreenPageLogo = NULL; imageLogo = NULL;
                }
                s_intro_shown = true;
            }
            if (ui_LabelIntroWord) {
                static const char *words[] = {"", "RACE", "AS", "ONE"};
                uint8_t pos = nvs_device_position_get();
                if (pos < 1 || pos > 3) pos = 1;
                lv_label_set_text(ui_LabelIntroWord, (s_intro_step >= pos + 1) ? words[pos] : "");
            }
        } else if (s_intro_step == 255 && !in_showroom_intro) {
            boot_enter_default_page();   // 仅开机时进默认页; showroom 不跳走
        }
        // s_intro_step==0: 仍在 Logo 等待
    }

    /* ---- 转速超限闪烁报警 ---- */
    {
        uint16_t warn_thresh = user_cfg->rpm_warn_threshold;
        if (warn_thresh < 1000) warn_thresh = 6000;
        bool over = (!IN_SWEEP && user_cfg->rpm_warn_anim_en && usRpm >= warn_thresh);
        // 测试模式: 强制触发
        if (s_rpm_flash_test_ticks > 0) { over = true; s_rpm_flash_test_ticks--; }

        // 背景图闪烁: img1→黑→img2→黑→img3→黑 循环, UI控件在图片上方正常显示
#if USE_CUSTOM_RPM_FLASH == 1
        static int8_t s_flash_step = -1;
        static const lv_img_dsc_t *s_flash_imgs[3] = { &imgRpmFlash1, &imgRpmFlash2, &imgRpmFlash3 };
#endif

#if USE_CUSTOM_RPM_FLASH == 1
        if (over) {
            if (s_flash_step < 0) s_flash_step = 0;
            lv_obj_t *scr = lv_scr_act();
            if (s_flash_step & 1) {
                lv_obj_set_style_bg_img_src(scr, NULL, LV_PART_MAIN);
                lv_obj_set_style_bg_color(scr, lv_color_hex(0x000000), LV_PART_MAIN);
                lv_obj_set_style_bg_opa(scr, 255, LV_PART_MAIN);
            } else {
                lv_obj_set_style_bg_img_src(scr, s_flash_imgs[(s_flash_step / 2) % 3], LV_PART_MAIN);
                lv_obj_set_style_bg_opa(scr, 255, LV_PART_MAIN);
            }
            s_flash_step = (s_flash_step + 1) % 6;
            s_rpm_flash_red = true;
        } else {
            if (s_flash_step >= 0) {
                lv_obj_t *scr = lv_scr_act();
                lv_obj_set_style_bg_img_src(scr, NULL, LV_PART_MAIN);
                lv_obj_set_style_bg_color(scr, lv_color_hex(0x000000), LV_PART_MAIN);
                lv_obj_set_style_bg_opa(scr, 255, LV_PART_MAIN);
                s_flash_step = -1;
            }
            s_rpm_flash_red = false;
        }
#else
        if (over) {
            s_rpm_flash_red = !s_rpm_flash_red;
            lv_obj_t *scr = lv_scr_act();
            lv_obj_set_style_bg_color(scr, s_rpm_flash_red ? lv_color_hex(0xFF0000) : lv_color_hex(0x000000), LV_PART_MAIN);
            lv_obj_set_style_bg_opa(scr, 255, LV_PART_MAIN);
        } else {
            if (s_rpm_flash_red) {
                lv_obj_set_style_bg_color(lv_scr_act(), lv_color_hex(0x000000), LV_PART_MAIN);
                lv_obj_set_style_bg_opa(lv_scr_act(), 255, LV_PART_MAIN);
                s_rpm_flash_red = false;
            }
        }
#endif
    }

    /* ---- 自适应刷新频率: 配置/静态页降频省重绘, 其余保持 200ms ----
       仅调整本 UI 定时器周期(纯重绘节奏), 不影响任何 OBD/RS485/ESP-NOW 查询与广播。
       数据是 OBD 限速的, 数据页刷更快无收益; 只对静态页降频, 纯赚 CPU/功耗。 */
    if (timer) {
        static uint32_t s_refresh_ms = 200;
        uint32_t want_ms;
        if (IN_SWEEP) {
            want_ms = SWEEP_TICK_MS;   // 扫表动画期间高刷, 让数字平滑递增
        } else if (s_rpm_flash_red) {
            want_ms = 1;    // 闪烁极限频率, LVGL自限到渲染+SPI极限
        } else {
            want_ms = 200;
            lv_obj_t *scr = lv_scr_act();
            if (scr == ui_ScreenPageSettings || scr == ui_ScreenPageMultiGauge ||
                scr == ui_ScreenPageEasterEgg || scr == ui_ScreenPageNeedleConfig ||
                scr == ui_ScreenPageBLEScan || scr == ui_ScreenPageODBProtocal ||
                scr == ui_ScreenPageTempCustom || scr == ui_ScreenPageInfoCustom ||
                scr == ui_ScreenPageOilWarn ||
                scr == ui_ScreenPageRpmWarn) {
                want_ms = 400;   // 设置/信息/配置/警告类静态页: 降频
            }
        }
        if (want_ms != s_refresh_ms) {
            s_refresh_ms = want_ms;
            lv_timer_set_period(timer, want_ms);
        }
    }
    #undef IN_SWEEP
}
///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////



///////////////////// FUNCTIONS ////////////////////
void ui_event_logo_background(lv_event_t * e)
{  
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        static uint32_t last_click_tick = 0;
        static uint8_t  click_cnt = 0;
        uint32_t now = lv_tick_get();
        if(now - last_click_tick < 400){
            click_cnt++;
        }else{
            click_cnt = 1;
        }
        last_click_tick = now;

        if(click_cnt >= 2){
            click_cnt = 0;
            if(ui_ScreenPageODBProtocal == NULL) ui_ScreenPageODBProtocal_screen_init();
            lv_scr_load_anim(ui_ScreenPageODBProtocal, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, true);
            ui_ScreenPageLogo = NULL;
            imageLogo = NULL;
        }  

        ESP_LOGD(TAG, "Logo LV_EVENT_CLICKED");
    }   
}

// 档位/转速/车速 三页位于轮播最前：档位→转速→车速→Temp→… (左滑下一页/右滑上一页)
void ui_event_gear_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageRpm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpm_screen_init);
        }
    }
}
void ui_event_rpm_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageGear, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGear_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSpeed, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSpeed_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageRpmWarn, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpmWarn_screen_init);
        }
    }
}
void ui_event_speed_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageRpm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpm_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
    }
}
// 轮播顺序: 档位 → 转速 → 车速 → Temp → Info → 仪表 → 机油压 → 刹车温度 → 版本页 → 回到 档位
// 左滑=下一页, 右滑=上一页
void ui_event_temp_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSpeed, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSpeed_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTempCustom, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTempCustom_screen_init);
        }
    }
}

void ui_event_temp_custom_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if (dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
    }
}

void ui_event_oil_pressure_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageNeedle, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedle_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            // 刹车温页已并入曲线页, 左滑到环下一个可见页(版本页)
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            // 下滑 → 曲线数据源选择页(删旧实例强制重建, 反映当前数据项/选择)
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_ScreenPageChartConfig) { lv_obj_del(ui_ScreenPageChartConfig); ui_ScreenPageChartConfig = NULL; }
            _ui_screen_change(&ui_ScreenPageChartConfig, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageChartConfig_screen_init);
        }
        else if(dir == LV_DIR_TOP) {
            // 上滑 → 报警阈值设置页(删旧实例强制重建, 按当前数据项)
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_ScreenPageChartAlarm) { lv_obj_del(ui_ScreenPageChartAlarm); ui_ScreenPageChartAlarm = NULL; }
            _ui_screen_change(&ui_ScreenPageChartAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageChartAlarm_screen_init);
        }
    }
}

// 曲线数据源选择页手势: 任意方向返回曲线页
void ui_event_chart_config_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
    }
}

// 曲线报警设置页手势: 任意方向返回曲线页
void ui_event_chart_alarm_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
    }
}

void ui_event_oil_warn_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
        }
    }
}

void ui_event_rpm_warn_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageRpm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpm_screen_init);
        }
    }
}

// 指针页(仪表)：位于 Info 与 OilPressure 之间(两曲线页之前)
//  右滑 → Info，左滑 → OilPressure，下滑 → 数据源选择
void ui_event_needle_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_BOTTOM){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageNeedleConfig, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedleConfig_screen_init);
        }
        else if(dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
        }
        else if(dir == LV_DIR_LEFT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
        }
    }
}

// 指针配置页：任意方向返回指针页
void ui_event_needle_config_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageNeedle, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedle_screen_init);
    }
}

void ui_event_info_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageNeedle, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageNeedle_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfoCustom, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfoCustom_screen_init);
        }
    }
}

void ui_event_info_custom_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if (dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
        }
    }
}
void ui_event_easter_egg_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED && !s_showroom_active) {
        showroom_handle_tap();  // 版本页连点10下进入 showroom
        return;
    }
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            // 刹车温页已并入曲线页, 版本页右滑回到曲线页
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageOilPressure, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageOilPressure_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageGear, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGear_screen_init);
        }
        else if(dir == LV_DIR_TOP) {
            // 上滑 → BLE 扫描页面
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageBLEScan, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageBLEScan_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            // 下滑 → 设置页面
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSettings, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSettings_screen_init);
        }
    }

    // ---- 手写扩展逻辑 hook (ui_ext.c, 不被 SquareLine 覆盖) ----
    ui_ext_tick();
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenPageLogo_screen_init();
    // Main 三合一页仍移除；车速/转速/档位三页恢复
    ui_ScreenPageGear_screen_init();
    ui_ScreenPageRpm_screen_init();
    ui_ScreenPageSpeed_screen_init();
    ui_ScreenPageTemp_screen_init();
    // 刹车温独立页已并入通用曲线页, 不再创建(其数据可在曲线页选择显示)
    ui_ScreenPageOilPressure_screen_init();   // 通用曲线页(内部按 chart_source_idx 配置)
    ui_ScreenPageOilWarn_screen_init();
    ui_ScreenPageODBProtocal_screen_init();
    ui_ScreenPageNeedle_screen_init();
    // Info 页按需懒加载，screen 指针须初始化为 NULL
    ui_ScreenPageInfo = NULL;
    ui_ScreenPageTempCustom = NULL;
    ui_ScreenPageInfoCustom = NULL;
    ui_ScreenPageNeedleConfig = NULL;   // 配置页懒加载
    ui_ScreenPageMultiGauge = NULL;     // 三连表设置页懒加载
    ui_ScreenPageChartConfig = NULL;    // 曲线数据源选择页懒加载
    ui_ScreenPageChartAlarm = NULL;     // 曲线报警设置页懒加载
    ui_ScreenPageIntro = NULL;          // 开机动画页懒加载
    ui____initial_actions0 = lv_obj_create(NULL);

    // 预创建默认启动页：开机切换前就建好，避免在过渡那一刻才同步创建导致卡顿。
    // 其余默认页(Temp/Brake/OilP/Needle/Gear/Rpm/Speed)上面已 eager 创建；只有 Info 是懒加载。
    if (nvs_cfg_get()->default_page == 1 && ui_ScreenPageInfo == NULL) {
        ui_ScreenPageInfo_screen_init();
    }

    lv_disp_load_scr(ui_ScreenPageLogo);

    lv_timer_create(my_timerMain, 100, NULL);  //100 ms 周期
}

/* OBD 协议页面事件 */
void ui_event_obd_prot_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
    }else if(code == LV_EVENT_LONG_PRESSED){
        usSaveProtTimeCnt = 0;
    }else if(code == LV_EVENT_LONG_PRESSED_REPEAT){
        usSaveProtTimeCnt += 100; // 该事件每 100 ms 触发一次
        if(usSaveProtTimeCnt >= SAVE_PROTOCOL_TIME){
            usSaveProtTimeCnt = 0;
            nvs_user_cfg_t cfg = *nvs_cfg_get();
            cfg.protocol = lv_roller_get_selected(ui_RollerODBProtocalChoose);
            nvs_cfg_set(&cfg);
            esp_restart();
        }
    }else if(code == LV_EVENT_RELEASED){
        usSaveProtTimeCnt = 0;
    }
}

/* BLE 扫描页面事件 - 左滑返回设备信息页 */
void ui_event_ble_scan_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            elm327_ble_scan_only_stop();
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
    }
}

/* 设置页面事件 - 左滑/右滑返回设备信息页 */
void ui_event_settings_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM){   // 下滑进入三连表设置页
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageMultiGauge, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageMultiGauge_screen_init);
        }
    }
}

// 三连表设置页手势: 上滑/左右滑 → 返回设置页
void ui_event_multi_gauge_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_TOP || dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSettings, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSettings_screen_init);
        }
    }
}
