// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
// UI主题命名为 PINK_CAT(粉色猫咪)，主色调为粉色，副色调为紫色
#include "ui.h"
#include "ui_helpers.h"
#include <driver/gpio.h>
#include "bsp_obd_dsp/bsp_board.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "bsp_obd_dsp/lcd_driver/ST77916.h"
#include "bsp_obd_dsp/elm327_ble_client.h"
#include "esp_system.h"
#include "esp_idf_version.h"


static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t * ui_ScreenPageLogo;
lv_obj_t * imageLogo;
lv_obj_t * imageEasterEgg;

// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
lv_obj_t * ui_ScreenPageMain;
lv_obj_t * ui_ImageMainPageback;
lv_obj_t * ui_SpinnerMainPage;
lv_obj_t * ui_ArcGearNumBack;
lv_obj_t * ui_LabelGeningRpmText;
lv_obj_t * ui_LabelGeningRpmUnitText;
lv_obj_t * ui_LabelCarSpeedText;
lv_obj_t * ui_LabelCarSpeedUnitText;
lv_obj_t * ui_ContainerMainPageBottomBlock;
lv_obj_t * ui_LabelGearNumText;
lv_obj_t * ui_ContainerMainPageMlieageBlock;
lv_obj_t * ui_LabelMainMlieageText;
lv_obj_t * ui_LabelMainMieageNum;
// CUSTOM VARIABLES
typedef enum {
    INFO_NONE = 0,
    INFO_TRIP,
    INFO_ODO,
    INFO_MAX,
    INFO_AVG,
    INFO_TIME,
    INFO_MODE_COUNT
} info_mode_t;

static info_mode_t s_info_mode = INFO_NONE; // 默认显示档位

static uint32_t s_trip_press_start = 0;


// SCREEN: ui_ScreenPageGear
void ui_ScreenPageGear_screen_init(void);
lv_obj_t * ui_ScreenPageGear;
lv_obj_t * ui_SpinnerGearPage;
lv_obj_t * ui_GearPageArcGearNumBack;
lv_obj_t * ui_GearPageArcLabelGearNumText;
lv_obj_t * ui_ImageGearBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageRpm
void ui_ScreenPageRpm_screen_init(void);
lv_obj_t * ui_ScreenPageRpm;
lv_obj_t * ui_SpinnerRpmPage;
lv_obj_t * ui_RpmPageArcRpmBack;
lv_obj_t * ui_RpmPageArcLabelRpmText;
lv_obj_t * ui_RpmPageArcLabelRpmUnit;
lv_obj_t * ui_ImageRpmBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageSpeed
void ui_ScreenPageSpeed_screen_init(void);
lv_obj_t * ui_ScreenPageSpeed;
lv_obj_t * ui_SpinnerSpeedPage;
lv_obj_t * ui_SpeedPageArcSpeedBack;
lv_obj_t * ui_SpeedPageArcLabelSpeedText;
lv_obj_t * ui_SpeedPageArcLabelSpeedUnit;
lv_obj_t * ui_ImageSpeedBlackEar;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenPageEasterEgg
void ui_ScreenPageEasterEgg_screen_init(void);
lv_obj_t * ui_ScreenPageEasterEgg;
lv_obj_t * ui_SpinnerEasterEgg;
lv_obj_t * ArcPageEasterEggBack;
lv_obj_t * ui_ImageEggBlackEar;
lv_obj_t * ui_LabelEasterEggInfo;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageBLEScan
void ui_ScreenPageBLEScan_screen_init(void);
lv_obj_t * ui_ScreenPageBLEScan;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageTemp
void ui_ScreenPageTemp_screen_init(void);
lv_obj_t * ui_ScreenPageTemp;

// SCREEN: ui_ScreenPageInfo
void ui_ScreenPageInfo_screen_init(void);
extern lv_obj_t * ui_ScreenPageInfo;
// labels defined in ui_ScreenPageInfo.c
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageSettings
void ui_ScreenPageSettings_screen_init(void);
lv_obj_t * ui_ScreenPageSettings;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageODBProtocal
void ui_ScreenPageODBProtocal_screen_init(void);
lv_obj_t * ui_ScreenPageODBProtocal;
lv_obj_t * ui_SpinnerODBProtocalEgg;
lv_obj_t * ui_ArcPageODBProtocalBack;
lv_obj_t * ui_RollerODBProtocalChoose;
lv_obj_t * ui_ImageODBProtocalBlackEar;
lv_obj_t * ui_LabelOBDIIText;
lv_obj_t * ui_LabelSureTipText;

// EVENTS
lv_obj_t * ui____initial_actions0;


static uint16_t usClearTripDataTimeCnt = 0;
static uint16_t usSaveProtTimeCnt = 0; //OBD协议保存计时

// IMAGES AND IMAGE SETS
#define CLEAR_TRIP_TIME 2000 //清除TRIP数据长按时间，单位ms
#define SAVE_PROTOCOL_TIME 2000 //保存协议长按时间ms
 
///////////////////// TEST LVGL SETTINGS ////////////////////
#define RPM_MAX 5000
#define SPEED_MAX 160

/* ---- Gauge sweep (刷表) animation ---- */
#define SWEEP_RPM_PEAK   8000   // 刷表最高转速
#define SWEEP_SPEED_PEAK 999    // 刷表最高车速
#define SWEEP_STEPS_UP   6      // 上升步数 (6×200ms = 1.2s)
#define SWEEP_STEPS_DOWN 6      // 下降步数
#define SWEEP_TOTAL      (SWEEP_STEPS_UP + SWEEP_STEPS_DOWN)
static int  s_sweep_step = 0;           // 0=关闭, 1~SWEEP_TOTAL=动画中
static bool s_sweep_pending = false;    // BLE 在 Logo 期间连上，Logo 消失后再触发
static bool s_prev_ble_connected = false;
void my_timerMain(lv_timer_t * timer)
{
    char *pGearNum[] = {"N","1", "2", "3", "4", "5", "6"};  // 6档支持
    static uint16_t usRpm = 0;
    static uint16_t ucSpeed = 0;  // uint16_t 以支持刷表时的999
    static enGear eGear = GEAR_NEUTRAL;
    static uint8_t ucOnlyOnce = 0;
    static uint32_t ulOpenLightTimeCnt = 0;

    /* ---- 一次性读取 OBD 数据，供温度页和 Info 页共用 ---- */
    int16_t clt      = obd_data_get_coolant_temp();
    int16_t iat      = obd_data_get_intake_temp();
    int16_t oil      = obd_data_get_oil_temp();      // 真实机油温度 °C (SSM 22 10 17), -100=无效
    int16_t load_pct = obd_data_get_load_pct();      // 发动机负荷 0~100%, -1=无效
    int16_t tps      = obd_data_get_tps();

    /* ---- 检测 BLE 连接，触发刷表 ---- */
    bool ble_now = elm327_ble_is_connected();
    if(ble_now && !s_prev_ble_connected) {
        if(ui_ScreenPageLogo == NULL) {
            s_sweep_step = 1;       // Logo 已结束，立即刷表
        } else {
            s_sweep_pending = true; // Logo 还在，先挂起
        }
    }
    s_prev_ble_connected = ble_now;

    /* ---- 数据来源：刷表 or 真实 OBD ---- */
    if(s_sweep_step > 0) {
        int step = s_sweep_step;
        float ratio;
        if(step <= SWEEP_STEPS_UP) {
            ratio = (float)step / (float)SWEEP_STEPS_UP;    // 0→1
        } else {
            ratio = (float)(SWEEP_TOTAL - step) / (float)SWEEP_STEPS_DOWN; // 1→0
        }
        usRpm   = (uint16_t)(SWEEP_RPM_PEAK * ratio);
        ucSpeed = (uint16_t)(SWEEP_SPEED_PEAK * ratio); // uint16_t 以支持999
        eGear   = (enGear)((int)(6.0f * ratio + 0.5f)); // 最高6档
        s_sweep_step++;
        if(s_sweep_step > SWEEP_TOTAL) s_sweep_step = 0; // 动画结束
    } else {
        usRpm   = obd_data_get_rpm();
        ucSpeed = obd_data_get_speed();
        eGear   = calculate_gear(usRpm, ucSpeed);
    }
    /*主页面*/
    lv_label_set_text_fmt(ui_LabelGeningRpmText, "%d", usRpm);
    lv_label_set_text_fmt(ui_LabelCarSpeedText, "%d", ucSpeed);
    lv_label_set_text_fmt (ui_LabelGearNumText, pGearNum[eGear]);
    if(s_info_mode == INFO_TRIP && usClearTripDataTimeCnt != 0)//清除TRIP数据时，显示清除进度
    {
        lv_arc_set_value(ui_ArcGearNumBack, (uint16_t)100*usClearTripDataTimeCnt/(CLEAR_TRIP_TIME/100));      
    }
    else//正常显示档位
    {
        lv_arc_set_value(ui_ArcGearNumBack, (uint16_t)eGear*100/6);  // 6档满盘
    }

/*档位页面*/
    lv_label_set_text_fmt(ui_GearPageArcLabelGearNumText, pGearNum[eGear]);
    lv_arc_set_value(ui_GearPageArcGearNumBack, (uint16_t)eGear*100/6);  // 6档满盘
 /*转速页面*/
    lv_label_set_text_fmt(ui_RpmPageArcLabelRpmText, "%d", usRpm);
    lv_arc_set_value(ui_RpmPageArcRpmBack, (uint32_t)usRpm*100/RPM_MAX);
 /*速度页面*/
    lv_label_set_text_fmt(ui_SpeedPageArcLabelSpeedText, "%d", ucSpeed);
    lv_arc_set_value(ui_SpeedPageArcSpeedBack, (uint32_t)ucSpeed*100/SPEED_MAX);

 /*温度页面*/
    if(ui_LabelCoolantTempText) {
        if(s_sweep_step > 0) {
            // 刷表期间: CLT/IAT/OIL 0→120→0°C
            int step = s_sweep_step - 1; // already incremented
            float r;
            if(step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = (float)(SWEEP_TOTAL - step) / (float)SWEEP_STEPS_DOWN;
            int16_t sweep_temp = (int16_t)(120.0f * r);
            lv_label_set_text_fmt(ui_LabelCoolantTempText, "%d", sweep_temp);
            lv_label_set_text_fmt(ui_LabelIntakeTempText,  "%d", sweep_temp);
            lv_label_set_text_fmt(ui_LabelOilTempText,     "%d", sweep_temp);
        } else {
            if(clt > -40)  lv_label_set_text_fmt(ui_LabelCoolantTempText, "%d", clt);
            else           lv_label_set_text(ui_LabelCoolantTempText, "--");
            if(iat > -40)  lv_label_set_text_fmt(ui_LabelIntakeTempText, "%d", iat);
            else           lv_label_set_text(ui_LabelIntakeTempText, "--");
            if(oil > -41)  lv_label_set_text_fmt(ui_LabelOilTempText, "%d", oil);
            else           lv_label_set_text(ui_LabelOilTempText, "--");
        }
    }

    /* Info 页更新 */
    if (ui_LabelInfoCLT) {
        if (s_sweep_step > 0) {
            // 刷表动画: CLT/IAT 0→120→0°C, LOAD/TPS 0→100→0%, BAT 12.0→14.4→12.0V
            int step = s_sweep_step - 1; // already incremented above
            float r;
            if (step <= SWEEP_STEPS_UP) r = (float)step / (float)SWEEP_STEPS_UP;
            else r = (float)(SWEEP_TOTAL - step) / (float)SWEEP_STEPS_DOWN;
            int16_t  sw_temp = (int16_t)(120.0f * r);
            int16_t  sw_pct  = (int16_t)(100.0f * r);
            lv_label_set_text_fmt(ui_LabelInfoCLT,  "%d", sw_temp);
            lv_label_set_text_fmt(ui_LabelInfoIAT,  "%d", sw_temp);
            lv_label_set_text_fmt(ui_LabelInfoLoad, "%d", sw_pct);
            lv_label_set_text_fmt(ui_LabelInfoTPS,  "%d", sw_pct);
            lv_label_set_text_fmt(ui_LabelInfoOil, "%d", sw_temp);  // 刷表时用温度动画
        } else {
            if (clt  > -40) lv_label_set_text_fmt(ui_LabelInfoCLT,  "%d", clt);
            else            lv_label_set_text(ui_LabelInfoCLT,  "--");
            if (iat  > -40) lv_label_set_text_fmt(ui_LabelInfoIAT,  "%d", iat);
            else            lv_label_set_text(ui_LabelInfoIAT,  "--");
            if (load_pct >= 0)   lv_label_set_text_fmt(ui_LabelInfoLoad, "%d", load_pct);
            else                  lv_label_set_text(ui_LabelInfoLoad, "--");
            if (tps  >= 0)  lv_label_set_text_fmt(ui_LabelInfoTPS,  "%d", tps);
            else            lv_label_set_text(ui_LabelInfoTPS,  "--");
            if (oil  > -41) lv_label_set_text_fmt(ui_LabelInfoOil, "%d", oil);
            else            lv_label_set_text(ui_LabelInfoOil, "--");
        }
    }

    /* 动态更新 EasterEgg 页面 BLE 信息 */
    if(ui_LabelEasterEggInfo) {
        const char *dev_name = elm327_ble_get_connected_name();
        if(!dev_name || dev_name[0] == '\0') dev_name = "Not set";
        lv_label_set_text_fmt(ui_LabelEasterEggInfo,
            "ESP32-S3  IDF %d.%d.%d\n"
            "LVGL %d.%d.%d\n"
            "BLE: %s\n"
            "Status: %s",
            ESP_IDF_VERSION_MAJOR, ESP_IDF_VERSION_MINOR, ESP_IDF_VERSION_PATCH,
            LVGL_VERSION_MAJOR, LVGL_VERSION_MINOR, LVGL_VERSION_PATCH,
            dev_name,
            ble_now ? "Connected" : "Disconnected");
    }
 
#if EXAMPLE_PIN_NUM_BK_LIGHT >= 0
        //等待500ms后开背光，避免没有初始化完成就开背光，只执行一次
        if(ucOnlyOnce == 0)
        {
            ulOpenLightTimeCnt++;
            if(ulOpenLightTimeCnt > 400 / 200)
            {
                const nvs_user_cfg_t *bl_cfg = nvs_cfg_get();
                uint8_t bright = bl_cfg->brightness_day;
                if(bright < 10) bright = 100;
                Set_Backlight(bright);
                ESP_LOGI(TAG, "Set LCD backlight to %d%%", bright);
                ulOpenLightTimeCnt = 0;
                ucOnlyOnce = 1;//只执行一次
            }
        }
#endif

    /* 底部信息栏更新 */
    nvs_stat_t stat = nvs_stat_get_mileage();
    switch(s_info_mode){
        case INFO_NONE:
            lv_obj_add_flag(ui_ContainerMainPageMlieageBlock, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_LabelGearNumText, LV_OBJ_FLAG_HIDDEN);
            break;
        case INFO_TRIP:
            lv_obj_clear_flag(ui_ContainerMainPageMlieageBlock, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_LabelGearNumText, LV_OBJ_FLAG_HIDDEN);
            lv_label_set_text_fmt(ui_LabelMainMlieageText, "%lld.%lld", stat.trip_m/1000, stat.trip_m/100%10);
            lv_label_set_text(ui_LabelMainMieageNum, "TRIP");
            break;
        case INFO_ODO:
            lv_obj_clear_flag(ui_ContainerMainPageMlieageBlock, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_LabelGearNumText, LV_OBJ_FLAG_HIDDEN);
            lv_label_set_text_fmt(ui_LabelMainMlieageText, "%lld", stat.odometer_m/1000);
            lv_label_set_text(ui_LabelMainMieageNum, "ODO");
            break;
        case INFO_MAX:
            lv_obj_clear_flag(ui_ContainerMainPageMlieageBlock, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_LabelGearNumText, LV_OBJ_FLAG_HIDDEN);
            lv_label_set_text_fmt(ui_LabelMainMlieageText, "%d", stat.max_speed_kmh);
            lv_label_set_text(ui_LabelMainMieageNum, "MAX");
            break;
        case INFO_AVG:
            lv_obj_clear_flag(ui_ContainerMainPageMlieageBlock, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_LabelGearNumText, LV_OBJ_FLAG_HIDDEN);
            lv_label_set_text_fmt(ui_LabelMainMlieageText, "%d", stat.avg_speed_kmh);
            lv_label_set_text(ui_LabelMainMieageNum, "AVG");
            break;
        case INFO_TIME:
            lv_obj_clear_flag(ui_ContainerMainPageMlieageBlock, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(ui_LabelGearNumText, LV_OBJ_FLAG_HIDDEN);
            uint32_t hrs = stat.run_time_s/3600;
            uint32_t mins = (stat.run_time_s%3600)/60;
            lv_label_set_text_fmt(ui_LabelMainMlieageText, "%02ld:%02ld", hrs, mins);
            lv_label_set_text(ui_LabelMainMieageNum, "TIME");
            break;
        default: break;
    }

    //在logo 页面 3s后自动跳转默认页面，并删除 Logo 屏幕释放内存
    if(ui_ScreenPageLogo)
    {
        static uint32_t ulLogoTimeCnt = 0;
        ulLogoTimeCnt++;
        if(ulLogoTimeCnt > 3000/200)
        {
            ulLogoTimeCnt = 0;
            const nvs_user_cfg_t *pg_cfg = nvs_cfg_get();
            lv_obj_t **target_scr = NULL;
            void (*target_init)(void) = NULL;
            switch(pg_cfg->default_page) {
                case 0: target_scr = &ui_ScreenPageTemp;  target_init = ui_ScreenPageTemp_screen_init;  break;
                case 1: target_scr = &ui_ScreenPageMain;  target_init = ui_ScreenPageMain_screen_init;  break;
                case 2: target_scr = &ui_ScreenPageGear;  target_init = ui_ScreenPageGear_screen_init;  break;
                case 3: target_scr = &ui_ScreenPageRpm;   target_init = ui_ScreenPageRpm_screen_init;   break;
                case 4: target_scr = &ui_ScreenPageSpeed; target_init = ui_ScreenPageSpeed_screen_init; break;
                case 5: target_scr = &ui_ScreenPageInfo;  target_init = ui_ScreenPageInfo_screen_init;  break;
                default: target_scr = &ui_ScreenPageTemp; target_init = ui_ScreenPageTemp_screen_init;  break;
            }
            if(*target_scr == NULL) target_init();
            lv_scr_load_anim(*target_scr, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, true);
            ui_ScreenPageLogo = NULL;
            imageLogo = NULL;
            // Logo 结束后检查是否有挂起的刷表请求
            if(s_sweep_pending) {
                s_sweep_pending = false;
                s_sweep_step = 1;
            }
        }
    }

}
///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////



///////////////////// FUNCTIONS ////////////////////
void ui_event_logo_background(lv_event_t * e)
{  
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        static uint32_t last_click_tick = 0;
        static uint8_t  click_cnt = 0;
        uint32_t now = lv_tick_get();
        if(now - last_click_tick < 400){
            click_cnt++;
        }else{
            click_cnt = 1;
        }
        last_click_tick = now;

        if(click_cnt >= 2){
            click_cnt = 0;
            if(ui_ScreenPageODBProtocal == NULL) ui_ScreenPageODBProtocal_screen_init();
            lv_scr_load_anim(ui_ScreenPageODBProtocal, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, true);
            ui_ScreenPageLogo = NULL;
            imageLogo = NULL;
        }  

        ESP_LOGI(TAG, "Logo LV_EVENT_CLICKED ! \n");
    }   
}

void ui_event_main_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageGear, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGear_screen_init);
        }else if(dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }else if(dir == LV_DIR_TOP){
            s_info_mode = (s_info_mode + 1) % INFO_MODE_COUNT;
        }else if(dir == LV_DIR_BOTTOM){
            s_info_mode = (s_info_mode + INFO_MODE_COUNT -1) % INFO_MODE_COUNT;
        }
    }
    else if(event_code == LV_EVENT_LONG_PRESSED)//按下500ms触发长按
    {
        s_trip_press_start = lv_tick_get();
        usClearTripDataTimeCnt = 0;
        ESP_LOGI(TAG, "LV_EVENT_LONG_PRESSED ! \n");
    }
    else if(event_code == LV_EVENT_LONG_PRESSED_REPEAT)//触发长按后，每100ms触发一次
    {
        ESP_LOGI(TAG, "LV_EVENT_LONG_PRESSED_REPEAT ! \n");
        //Trip 页面 && 速度为0 && Trip数据大于0.1km（100m）
        if(s_info_mode == INFO_TRIP && obd_data_get_speed() == 0 && nvs_stat_get_mileage().trip_m > 100)
        {
            usClearTripDataTimeCnt++;
            if(usClearTripDataTimeCnt >= CLEAR_TRIP_TIME/100)
            {
                usClearTripDataTimeCnt = 0;
                nvs_stat_reset_trip();
            }
        }
        else
        {
            usClearTripDataTimeCnt = 0;
        }
    }
    else if(event_code == LV_EVENT_RELEASED)//释放
    {
        ESP_LOGI(TAG, "LV_EVENT_RELEASED ! \n");
        if(usClearTripDataTimeCnt)
        {
            usClearTripDataTimeCnt = 0;        
        }
    }

}
void ui_event_gear_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageMain, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageMain_screen_init);  
    }
    else if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageRpm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpm_screen_init);  
    }
}
void ui_event_rpm_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageGear, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageGear_screen_init);  
    }
    else if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageSpeed, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSpeed_screen_init);  
    }
}
void ui_event_speed_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageRpm, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageRpm_screen_init); 
    }
    else if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);  
    }
}
void ui_event_temp_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSpeed, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSpeed_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
        }
    }
}
void ui_event_info_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageTemp, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageTemp_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
    }
}
void ui_event_easter_egg_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageInfo, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageInfo_screen_init);
        }
        else if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageMain, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageMain_screen_init);
        }
        else if(dir == LV_DIR_TOP) {
            // 上滑 → BLE 扫描页面
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageBLEScan, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageBLEScan_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            // 下滑 → 设置页面
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageSettings, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageSettings_screen_init);
        }
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenPageLogo_screen_init();
    ui_ScreenPageMain_screen_init();
    ui_ScreenPageGear_screen_init();
    ui_ScreenPageRpm_screen_init();
    ui_ScreenPageSpeed_screen_init();
    ui_ScreenPageTemp_screen_init();
    ui_ScreenPageODBProtocal_screen_init();
    // Info 页按需懒加载，screen 指针须初始化为 NULL
    ui_ScreenPageInfo = NULL;
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenPageLogo);

    lv_timer_create(my_timerMain, 200, NULL);  //200 ms 周期
}

/* OBD 协议页面事件 */
void ui_event_obd_prot_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageMain, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageMain_screen_init);
        }
    }else if(code == LV_EVENT_LONG_PRESSED){
        usSaveProtTimeCnt = 0;
    }else if(code == LV_EVENT_LONG_PRESSED_REPEAT){
        usSaveProtTimeCnt += 100; // 该事件每 100 ms 触发一次
        if(usSaveProtTimeCnt >= SAVE_PROTOCOL_TIME/100){
            usSaveProtTimeCnt = 0;
            nvs_user_cfg_t cfg = *nvs_cfg_get();
            cfg.protocol = lv_roller_get_selected(ui_RollerODBProtocalChoose);
            nvs_cfg_set(&cfg);
            esp_restart();
        }
    }else if(code == LV_EVENT_RELEASED){
        usSaveProtTimeCnt = 0;
    }
}

/* BLE 扫描页面事件 - 左滑返回设备信息页 */
void ui_event_ble_scan_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
    }
}

/* 设置页面事件 - 左滑/右滑返回设备信息页 */
void ui_event_settings_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageEasterEgg, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageEasterEgg_screen_init);
        }
    }
}
