// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#ifndef _OBD_PRJ_UI_H
#define _OBD_PRJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "esp_log.h"
#include "app_obd_dsp/obd_data_cache.h"

#define USE_GIF_LOGO        0
#define USE_GIF_EASTER_EGG  0
// 自定义开机图开关: 1=用客户自定义图片(imgBootLogoCustom)作开机动画; 0=用默认 SKY GAUGE
// 置 1 前需把客户 PNG 转成 LVGL C 数组(变量名 imgBootLogoCustom)放进 images/ 目录
#define USE_CUSTOM_BOOT_LOGO 0

#define COLOR_MITSUBISHI_RED    0xFFFFFF //主色调白色(原三菱红)
#define COLOR_DOMIANT_PINK      0xFFFFFF //主色调白色(原粉色)
#define COLOR_SECONDARY_PINK    0x333333 //副色调深灰(原暗粉)



void ui_ScreenPageLogo_screen_init(void);
extern lv_obj_t * ui_ScreenPageLogo;
extern lv_obj_t * imageLogo;

// SCREEN: ui_ScreenPageMain
void ui_ScreenPageMain_screen_init(void);
extern lv_obj_t * ui_ScreenPageMain;
extern lv_obj_t * ui_ImageMainPageback;
extern lv_obj_t * ui_SpinnerMainPage;
extern lv_obj_t * ui_ArcGearNumBack;
extern lv_obj_t * ui_LabelGeningRpmText;
extern lv_obj_t * ui_LabelGeningRpmUnitText;
extern lv_obj_t * ui_LabelCarSpeedText;
extern lv_obj_t * ui_LabelCarSpeedUnitText;
extern lv_obj_t * ui_ContainerMainPageBottomBlock;
extern lv_obj_t * ui_LabelGearNumText;
extern lv_obj_t * ui_ContainerMainPageMlieageBlock;
extern lv_obj_t * ui_LabelMainMlieageText;
extern lv_obj_t * ui_LabelMainMieageNum;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageGear
void ui_ScreenPageGear_screen_init(void);
extern lv_obj_t * ui_ScreenPageGear;
extern lv_obj_t * ui_SpinnerGearPage;
extern lv_obj_t * ui_GearPageArcGearNumBack;
extern lv_obj_t * ui_GearPageArcLabelGearNumText;
extern lv_obj_t * ui_ImageGearBlackEar;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageRpm
void ui_ScreenPageRpm_screen_init(void);
extern lv_obj_t * ui_ScreenPageRpm;
extern lv_obj_t * ui_SpinnerRpmPage;
extern lv_obj_t * ui_RpmPageArcRpmBack;
extern lv_obj_t * ui_RpmPageArcLabelRpmText;
extern lv_obj_t * ui_RpmPageArcLabelRpmUnit;
extern lv_obj_t * ui_ImageRpmBlackEar;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageSpeed
void ui_ScreenPageSpeed_screen_init(void);
extern lv_obj_t * ui_ScreenPageSpeed;
extern lv_obj_t * ui_SpinnerSpeedPage;
extern lv_obj_t * ui_SpeedPageArcSpeedBack;
extern lv_obj_t * ui_SpeedPageArcLabelSpeedText;
extern lv_obj_t * ui_SpeedPageArcLabelSpeedUnit;
extern lv_obj_t * ui_ImageSpeedBlackEar;
// CUSTOM VARIABLES
// SCREEN: ui_ScreenPageODBProtocal
void ui_ScreenPageODBProtocal_screen_init(void);
extern lv_obj_t * ui_ScreenPageODBProtocal;
extern lv_obj_t * ui_SpinnerODBProtocalEgg;
extern lv_obj_t * ui_ArcPageODBProtocalBack;
extern lv_obj_t * ui_RollerODBProtocalChoose;
extern lv_obj_t * ui_ImageODBProtocalBlackEar;
extern lv_obj_t * ui_LabelOBDIIText;
extern lv_obj_t * ui_LabelSureTipText;

// SCREEN: ui_ScreenPageEasterEgg
void ui_ScreenPageEasterEgg_screen_init(void);
extern lv_obj_t * ui_ScreenPageEasterEgg;
extern lv_obj_t * ui_SpinnerEasterEgg;
extern lv_obj_t * ArcPageEasterEggBack;
extern lv_obj_t * imageEasterEgg;
extern lv_obj_t * ui_ImageEggBlackEar;
extern lv_obj_t * ui_LabelEasterEggInfo;  // \u52a8\u6001\u66f4\u65b0\u7684\u8bbe\u5907\u4fe1\u606f\u6807\u7b7e
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageBLEScan
void ui_ScreenPageBLEScan_screen_init(void);
extern lv_obj_t * ui_ScreenPageBLEScan;
void ui_event_ble_scan_background(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageTemp
void ui_ScreenPageTemp_screen_init(void);
extern lv_obj_t * ui_ScreenPageTemp;
extern lv_obj_t * ui_LabelCoolantTempText;
extern lv_obj_t * ui_LabelOilTempText;
extern lv_obj_t * ui_LabelIntakeTempText;
extern lv_obj_t * ui_LabelTempValue[3];
extern lv_obj_t * ui_LabelTempName[3];
extern lv_obj_t * ui_LabelTempUnit[3];
extern lv_obj_t * ui_LabelTempDot[3];
void ui_event_temp_background(lv_event_t * e);

// SCREEN: ui_ScreenPageTempCustom
void ui_ScreenPageTempCustom_screen_init(void);
extern lv_obj_t * ui_ScreenPageTempCustom;
void ui_event_temp_custom_background(lv_event_t * e);

// SCREEN: ui_ScreenPageBrakeTemp
void ui_ScreenPageBrakeTemp_screen_init(void);
extern lv_obj_t * ui_ScreenPageBrakeTemp;
extern lv_obj_t * ui_LabelBrakeTempText;
extern lv_obj_t * ui_ChartBrakeTemp;
extern lv_chart_series_t * ui_BrakeTempChartSeries;
void ui_event_brake_temp_background(lv_event_t * e);

// SCREEN: ui_ScreenPageOilPressure
void ui_ScreenPageOilPressure_screen_init(void);
extern lv_obj_t * ui_ScreenPageOilPressure;
extern lv_obj_t * ui_LabelOilPressureText;
extern lv_obj_t * ui_ChartOilPressure;
extern lv_chart_series_t * ui_OilPressureChartSeries;
void ui_event_oil_pressure_background(lv_event_t * e);

// SCREEN: ui_ScreenPageInfo
void ui_ScreenPageInfo_screen_init(void);
extern lv_obj_t * ui_ScreenPageInfo;
extern lv_obj_t * ui_LabelInfoCLT;
extern lv_obj_t * ui_LabelInfoIAT;
extern lv_obj_t * ui_LabelInfoLoad;
extern lv_obj_t * ui_LabelInfoTPS;
extern lv_obj_t * ui_LabelInfoOil;
extern lv_obj_t * ui_LabelInfoValue[5];
extern lv_obj_t * ui_LabelInfoName[5];
extern lv_obj_t * ui_LabelInfoUnit[5];
void ui_event_info_background(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageInfoCustom
void ui_ScreenPageInfoCustom_screen_init(void);
extern lv_obj_t * ui_ScreenPageInfoCustom;
void ui_event_info_custom_background(lv_event_t * e);

// SCREEN: ui_ScreenPageSettings
void ui_ScreenPageSettings_screen_init(void);
extern lv_obj_t * ui_ScreenPageSettings;
void ui_event_settings_background(lv_event_t * e);
// CUSTOM VARIABLES

// SCREEN: ui_ScreenPageBrakeWarn
void ui_ScreenPageBrakeWarn_screen_init(void);
extern lv_obj_t * ui_ScreenPageBrakeWarn;
void ui_event_brake_warn_background(lv_event_t * e);

// SCREEN: ui_ScreenPageOilWarn
void ui_ScreenPageOilWarn_screen_init(void);
extern lv_obj_t * ui_ScreenPageOilWarn;
void ui_event_oil_warn_background(lv_event_t * e);

// SCREEN: ui_ScreenPageNeedle (指针式可配置仪表)
void ui_ScreenPageNeedle_screen_init(void);
extern lv_obj_t * ui_ScreenPageNeedle;
void ui_event_needle_background(lv_event_t * e);
// 指针页控件 (由 screen_init 创建, ui.c 的定时器刷新)
extern lv_obj_t * ui_NeedleMeter;
extern lv_meter_scale_t * ui_NeedleScale;
extern lv_meter_indicator_t * ui_NeedleIndic;
extern lv_obj_t * ui_NeedleValueLabel;
extern lv_obj_t * ui_NeedleNameLabel;
extern lv_obj_t * ui_NeedleUnitLabel;

// SCREEN: ui_ScreenPageNeedleConfig (下滑进入的数据源选择)
void ui_ScreenPageNeedleConfig_screen_init(void);
extern lv_obj_t * ui_ScreenPageNeedleConfig;
void ui_event_needle_config_background(lv_event_t * e);

// SCREEN: ui_ScreenPageMultiGauge (设置页下滑进入: 三连表 主/从 + 选主表)
void ui_ScreenPageMultiGauge_screen_init(void);
extern lv_obj_t * ui_ScreenPageMultiGauge;
void ui_event_multi_gauge_background(lv_event_t * e);

// 指针页运行时接口 (ui.c 实现, 复用 disp_item 系统)
void ui_needle_page_update(float sweep_ratio);   // 每帧刷新指针与数值 (sweep_ratio<0=实时, 0~1=刷表自检)
void ui_needle_apply_source(void);  // 数据源变化后重建量程/名称/单位
int  ui_sweep_get_step(void);       // 取当前扫表进度(主表广播给从表)
void ui_sweep_set_step(int step);   // 设扫表进度(从表跟随主表广播, 实现同步扫表)
const char *ui_disp_item_name(uint8_t item); // 取数据项显示名 (越界返回 "")

// EVENTS

extern lv_obj_t * ui____initial_actions0;
LV_IMG_DECLARE(gifBlueLightLogo);    
LV_IMG_DECLARE(gifSnake400);  
LV_IMG_DECLARE(gifKaBiBaLaZip);    // assets/pngBlueLightLogo.png
LV_IMG_DECLARE(gifCuteCatZip);
LV_IMG_DECLARE(gifBlackLeopard);
// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pngmainback_png);    // assets/pngMainBack.png
LV_IMG_DECLARE(pngLogoMITSUBISHI);    // assets/pngLogoMITSUBISHI.png
LV_IMG_DECLARE(pngLogoSkyGarage);     // assets/sklogo.png (280x280)
#if USE_CUSTOM_BOOT_LOGO == 1
LV_IMG_DECLARE(imgBootLogoCustom);    // 客户自定义开机图(需自行转换并放入 images/)
#endif
LV_IMG_DECLARE(ui_img_pngblackear_png);    // assets/pngBlackEar.png
// FONTS
LV_FONT_DECLARE(ui_font_FontBabyGearNumSize48);
LV_FONT_DECLARE(ui_font_FontBabySize108);
LV_FONT_DECLARE(ui_font_FontBabySize156);
LV_FONT_DECLARE(ui_font_FontBabySize180);
LV_FONT_DECLARE(ui_font_FontBabySize200);
LV_FONT_DECLARE(ui_font_FontBabySize56);
LV_FONT_DECLARE(ui_font_FontTaikongSize108);
LV_FONT_DECLARE(ui_font_FontTaikongSize128);
LV_FONT_DECLARE(ui_font_FontTaikongSize32);
LV_FONT_DECLARE(ui_font_FontTaikongSize40);
LV_FONT_DECLARE(ui_font_FontTaikongSize48);
LV_FONT_DECLARE(ui_font_FontTaikongSize56);
LV_FONT_DECLARE(ui_font_FontTaikongSize64);
LV_FONT_DECLARE(ui_font_FontTaikongSize72);
LV_FONT_DECLARE(ui_font_FontTypoderSize16);
LV_FONT_DECLARE(ui_font_FontTypoderSize20);
LV_FONT_DECLARE(ui_font_FontTypoderSize24);
LV_FONT_DECLARE(ui_font_FontTypoderSize28);
LV_FONT_DECLARE(ui_font_FontTypoderSize32);
LV_FONT_DECLARE(ui_font_FontTypoderSize36);
LV_FONT_DECLARE(ui_font_FontTypoderSize40);
LV_FONT_DECLARE(ui_font_FontTypoderSize44);
LV_FONT_DECLARE(ui_font_FontTypoderSize56);
LV_FONT_DECLARE(ui_font_FontTypoderSize100);
LV_FONT_DECLARE(ui_font_FontTypoderSize140);


// UI INIT
void ui_init(void);
void ui_event_logo_background(lv_event_t * e);
void ui_event_main_background(lv_event_t * e);
void ui_event_gear_background(lv_event_t * e);
void ui_event_rpm_background(lv_event_t * e);
void ui_event_speed_background(lv_event_t * e);
void ui_event_obd_prot_background(lv_event_t * e);
void ui_event_easter_egg_background(lv_event_t * e);
void ui_event_temp_background(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
