// ============================================================
//  ui_theme_generated.c — GENERATED FILE, DO NOT EDIT
//
//  Produced by tools/gen_themes.py from:
//    themes/registry.txt          (slot -> id, append only)
//    themes/*/<id>/theme.toml     (per-theme manifest)
//
//  To add a theme: create the folder + manifest, append one line to
//  registry.txt, rebuild. Do not edit this file — it is overwritten at
//  every CMake configure.
//
//  3 theme(s), slots 0..2.
// ============================================================

#include "ui_theme.h"

// slot 0 — themes/builtin/default/theme.toml
// Original black face with a white bezel ring.
// author: steveEcode
static const ui_theme_t s_theme_default = {
    .id   = "default",
    .name = "DEFAULT",
    .colors = {
        [UI_COLOR_BG]             = 0x000000,
        [UI_COLOR_RING]           = 0xFFFFFF,
        [UI_COLOR_ARC_TRACK]      = 0x333333,
        [UI_COLOR_ARC_INDICATOR]  = 0xFFFFFF,
        [UI_COLOR_TEXT_PRIMARY]   = 0xFFFFFF,
        [UI_COLOR_TEXT_SECONDARY] = 0x888888,
        [UI_COLOR_NEEDLE]         = 0xFF1010,
        [UI_COLOR_PANEL]          = 0x222222,
    },
    .bezel = { .style_id = 0 },
};

// slot 1 — themes/builtin/amber/theme.toml
// Classic warm amber, dark brown face.
// author: steveEcode
static const ui_theme_t s_theme_amber = {
    .id   = "amber",
    .name = "AMBER",
    .colors = {
        [UI_COLOR_BG]             = 0x0A0700,
        [UI_COLOR_RING]           = 0xFFB000,
        [UI_COLOR_ARC_TRACK]      = 0x3A2E10,
        [UI_COLOR_ARC_INDICATOR]  = 0xFFB000,
        [UI_COLOR_TEXT_PRIMARY]   = 0xFFD27A,
        [UI_COLOR_TEXT_SECONDARY] = 0x9A7B3A,
        [UI_COLOR_NEEDLE]         = 0xFF5A1F,
        [UI_COLOR_PANEL]          = 0x241C08,
    },
    .bezel = { .style_id = 0 },
};

// slot 2 — themes/builtin/ocean/theme.toml
// Cool cyan-blue on a near-black face.
// author: steveEcode
static const ui_theme_t s_theme_ocean = {
    .id   = "ocean",
    .name = "OCEAN",
    .colors = {
        [UI_COLOR_BG]             = 0x000508,
        [UI_COLOR_RING]           = 0x33CCFF,
        [UI_COLOR_ARC_TRACK]      = 0x10303C,
        [UI_COLOR_ARC_INDICATOR]  = 0x33CCFF,
        [UI_COLOR_TEXT_PRIMARY]   = 0xBFEFFF,
        [UI_COLOR_TEXT_SECONDARY] = 0x4E7C8C,
        [UI_COLOR_NEEDLE]         = 0x66AAFF,
        [UI_COLOR_PANEL]          = 0x0A1E26,
    },
    .bezel = { .style_id = 0 },
};

// Registry — index IS the slot number stored in NVS (theme_cfg.theme).
const ui_theme_t *const g_ui_themes[] = {
    &s_theme_default,  // slot 0
    &s_theme_amber,    // slot 1
    &s_theme_ocean,    // slot 2
};

const uint8_t g_ui_theme_count = 3;
