#!/usr/bin/env python3

from pathlib import Path
from PIL import Image

SOURCE_DIR = Path("assets/boot86/processed")
OUTPUT_DIR = Path("main/export_path/images")

ASSETS = [
    (
        "boot86_gr_black_360.png",
        "imgBoot86GRBlack.c",
        "imgBoot86GRBlack",
        "IMG_BOOT86_GR_BLACK",
    ),
    (
        "boot86_gr_red_360.png",
        "imgBoot86GRRed.c",
        "imgBoot86GRRed",
        "IMG_BOOT86_GR_RED",
    ),
    (
        "boot86_gr_text_360.png",
        "imgBoot86GRText.c",
        "imgBoot86GRText",
        "IMG_BOOT86_GR_TEXT",
    ),
    (
        "boot86_dial_ring_360.png",
        "imgBoot86DialRing.c",
        "imgBoot86DialRing",
        "IMG_BOOT86_DIAL_RING",
    ),
    (
        "boot86_logo_86_360.png",
        "imgBoot86Logo86.c",
        "imgBoot86Logo86",
        "IMG_BOOT86_LOGO86",
    ),
    (
        "boot86_gr_logo_360.png",
        "imgBoot86GRLogo.c",
        "imgBoot86GRLogo",
        "IMG_BOOT86_GR_LOGO",
    ),
    (
        "boot86_gr_logo_motion_blur_360.png",
        "imgBoot86GRLogoMotionBlur.c",
        "imgBoot86GRLogoMotionBlur",
        "IMG_BOOT86_GR_LOGO_MOTION_BLUR",
    ),
    (
        "boot86_logo_86_motion_blur_360.png",
        "imgBoot86Logo86MotionBlur.c",
        "imgBoot86Logo86MotionBlur",
        "IMG_BOOT86_LOGO_86_MOTION_BLUR",
    ),
]


def convert_image(
    source_path: Path,
    output_path: Path,
    variable_name: str,
    attribute_name: str,
) -> None:
    image = Image.open(source_path).convert("RGBA")

    if image.size != (360, 360):
        raise RuntimeError(
            f"{source_path} 尺寸为 {image.size}，必须是 360x360"
        )

    width, height = image.size
    pixels = image.load()

    with output_path.open("w", encoding="utf-8", newline="\n") as file:
        file.write("// Auto-generated by tools/convert_boot86_assets.py\n")
        file.write(f"// Source: {source_path}\n")
        file.write("// Full 360x360 canvas preserved\n")
        file.write("// Pixel format: RGB565 little-endian + alpha\n\n")

        file.write("#ifdef __has_include\n")
        file.write('    #if __has_include("lvgl.h")\n')
        file.write("        #ifndef LV_LVGL_H_INCLUDE_SIMPLE\n")
        file.write("            #define LV_LVGL_H_INCLUDE_SIMPLE\n")
        file.write("        #endif\n")
        file.write("    #endif\n")
        file.write("#endif\n\n")

        file.write("#if defined(LV_LVGL_H_INCLUDE_SIMPLE)\n")
        file.write('#include "lvgl.h"\n')
        file.write("#else\n")
        file.write('#include "lvgl/lvgl.h"\n')
        file.write("#endif\n\n")

        file.write(f"#ifndef LV_ATTRIBUTE_IMG_{attribute_name}\n")
        file.write(f"#define LV_ATTRIBUTE_IMG_{attribute_name}\n")
        file.write("#endif\n\n")

        file.write(
            "const LV_ATTRIBUTE_MEM_ALIGN "
            "LV_ATTRIBUTE_LARGE_CONST "
            f"LV_ATTRIBUTE_IMG_{attribute_name} "
            f"uint8_t {variable_name}_map[] = {{\n"
        )

        pixels_per_line = 8
        pixel_index = 0

        for y in range(height):
            for x in range(width):
                red, green, blue, alpha = pixels[x, y]

                rgb565 = (
                    ((red & 0xF8) << 8)
                    | ((green & 0xFC) << 3)
                    | (blue >> 3)
                )

                high = (rgb565 >> 8) & 0xFF
                low = rgb565 & 0xFF

                if pixel_index % pixels_per_line == 0:
                    file.write("    ")

                file.write(
                    f"0x{low:02X}, 0x{high:02X}, 0x{alpha:02X}"
                )

                is_last = (
                    x == width - 1
                    and y == height - 1
                )

                if not is_last:
                    file.write(", ")

                pixel_index += 1

                if pixel_index % pixels_per_line == 0:
                    file.write("\n")

        if pixel_index % pixels_per_line != 0:
            file.write("\n")

        file.write("};\n\n")

        file.write(f"const lv_img_dsc_t {variable_name} = {{\n")
        file.write("    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n")
        file.write("    .header.always_zero = 0,\n")
        file.write("    .header.reserved = 0,\n")
        file.write("    .header.w = 360,\n")
        file.write("    .header.h = 360,\n")
        file.write(f"    .data_size = sizeof({variable_name}_map),\n")
        file.write(f"    .data = {variable_name}_map,\n")
        file.write("};\n")

    print(
        f"生成: {output_path} "
        f"({width}x{height}, {width * height * 3} bytes)"
    )


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for source_name, output_name, variable_name, attribute_name in ASSETS:
        source_path = SOURCE_DIR / source_name
        output_path = OUTPUT_DIR / output_name

        if not source_path.exists():
            raise FileNotFoundError(f"找不到素材：{source_path}")

        convert_image(
            source_path,
            output_path,
            variable_name,
            attribute_name,
        )


if __name__ == "__main__":
    main()
