#!/usr/bin/env python3
"""Convert 3 PNG images to LVGL RGB565 C arrays for RPM flash animation.
Usage: python3 tools/convert_rpm_flash.py <img1.png> <img2.png> <img3.png>
Output: main/export_path/images/imgRpmFlash{1,2,3}.c
"""
import sys
from PIL import Image

def convert_png_to_c(png_path, c_path, var_name, attr_name):
    img = Image.open(png_path).convert('RGB').resize((360, 360), Image.LANCZOS)
    pixels = img.load()

    with open(c_path, 'w') as f:
        f.write(f'// Auto-generated by convert_rpm_flash.py\n')
        f.write(f'// Source: {png_path} resized to 360x360\n')
        f.write(f'// LV_COLOR_16_SWAP=1: big-endian byte order (hi, lo)\n\n')
        f.write('#ifdef __has_include\n')
        f.write('    #if __has_include("lvgl.h")\n')
        f.write('        #ifndef LV_LVGL_H_INCLUDE_SIMPLE\n')
        f.write('            #define LV_LVGL_H_INCLUDE_SIMPLE\n')
        f.write('        #endif\n')
        f.write('    #endif\n')
        f.write('#endif\n\n')
        f.write('#if defined(LV_LVGL_H_INCLUDE_SIMPLE)\n')
        f.write('#include "lvgl.h"\n')
        f.write('#else\n')
        f.write('#include "lvgl/lvgl.h"\n')
        f.write('#endif\n\n')
        f.write(f'#ifndef LV_ATTRIBUTE_IMG_{attr_name}\n')
        f.write(f'#define LV_ATTRIBUTE_IMG_{attr_name}\n')
        f.write('#endif\n\n')
        f.write(f'const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_{attr_name} uint8_t {var_name}_map[] = {{\n')

        for y in range(360):
            f.write('  ')
            for x in range(360):
                r, g, b = pixels[x, y]
                rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
                hi = (rgb565 >> 8) & 0xFF
                lo = rgb565 & 0xFF
                f.write(f'0x{hi:02X}, 0x{lo:02X}')
                if x < 359 or y < 359:
                    f.write(', ')
            f.write('\n')

        f.write('};\n\n')
        f.write(f'const lv_img_dsc_t {var_name} = {{\n')
        f.write('  .header.cf = LV_IMG_CF_TRUE_COLOR,\n')
        f.write('  .header.always_zero = 0,\n')
        f.write('  .header.reserved = 0,\n')
        f.write('  .header.w = 360,\n')
        f.write('  .header.h = 360,\n')
        f.write(f'  .data_size = sizeof({var_name}_map),\n')
        f.write(f'  .data = {var_name}_map,\n')
        f.write('};\n')

    print(f'  OK: {c_path}')

if __name__ == '__main__':
    if len(sys.argv) != 4:
        print(f'Usage: {sys.argv[0]} <1.png> <2.png> <3.png>')
        sys.exit(1)

    base = 'main/export_path/images'
    convert_png_to_c(sys.argv[1], f'{base}/imgRpmFlash1.c', 'imgRpmFlash1', 'IMGFLASH1')
    convert_png_to_c(sys.argv[2], f'{base}/imgRpmFlash2.c', 'imgRpmFlash2', 'IMGFLASH2')
    convert_png_to_c(sys.argv[3], f'{base}/imgRpmFlash3.c', 'imgRpmFlash3', 'IMGFLASH3')
    print('Done! All 3 flash images converted.')
