#!/usr/bin/env python3
"""Convert a PNG image to an LVGL RGB565 C array using project-relative paths."""

from pathlib import Path
import sys
from PIL import Image
import struct

PROJECT_ROOT = Path(__file__).resolve().parents[1]
INPUT_FILE = PROJECT_ROOT / "tools" / "sklogo.png"
OUTPUT_FILE = PROJECT_ROOT / "main" / "export_path" / "images" / "pngLogoSkyGarage.c"
VAR_NAME = "pngLogoSkyGarage"
TARGET_SIZE = (280, 280)  # fit in 360x360 screen

def rgb888_to_rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def main():
    if not INPUT_FILE.exists():
        raise FileNotFoundError(f"Input file not found: {INPUT_FILE}")

    img = Image.open(INPUT_FILE).convert("RGBA")
    # Resize with high quality
    img = img.resize(TARGET_SIZE, Image.LANCZOS)
    w, h = img.size

    # Composite onto black background - no transparency, no fringe
    bg = Image.new("RGB", (w, h), (0, 0, 0))
    bg.paste(img, mask=img.split()[3])  # use alpha as mask
    pixels = list(bg.getdata())

    print(f"Image: {w}x{h}, {len(pixels)} pixels (composited on black, no alpha)")

    # Build raw data: for each pixel, output 2 bytes: [low_byte_rgb565, high_byte_rgb565]
    # No alpha channel - CF_TRUE_COLOR format
    raw = bytearray()
    for r, g, b in pixels:
        c565 = rgb888_to_rgb565(r, g, b)
        raw.append(c565 & 0xFF)
        raw.append((c565 >> 8) & 0xFF)

    # Generate C file
    lines = []
    lines.append("// Auto-generated by png_to_lvgl.py")
    lines.append(f"// Source: {INPUT_FILE.name} resized to {w}x{h}")
    lines.append("")
    lines.append('#ifdef __has_include')
    lines.append('    #if __has_include("lvgl.h")')
    lines.append('        #ifndef LV_LVGL_H_INCLUDE_SIMPLE')
    lines.append('            #define LV_LVGL_H_INCLUDE_SIMPLE')
    lines.append('        #endif')
    lines.append('    #endif')
    lines.append('#endif')
    lines.append("")
    lines.append('#if defined(LV_LVGL_H_INCLUDE_SIMPLE)')
    lines.append('#include "lvgl.h"')
    lines.append('#else')
    lines.append('#include "lvgl/lvgl.h"')
    lines.append('#endif')
    lines.append("")
    lines.append(f"#ifndef LV_ATTRIBUTE_IMG_{VAR_NAME.upper()}")
    lines.append(f"#define LV_ATTRIBUTE_IMG_{VAR_NAME.upper()}")
    lines.append("#endif")
    lines.append("")
    lines.append(f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_{VAR_NAME.upper()} uint8_t {VAR_NAME}_map[] = {{")

    # Write data in rows of 16 pixels per line
    BYTES_PER_LINE = 32  # 16 pixels * 2 bytes (RGB565, no alpha)
    for i in range(0, len(raw), BYTES_PER_LINE):
        chunk = raw[i:i+BYTES_PER_LINE]
        hex_str = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_str},")

    lines.append("};")
    lines.append("")
    lines.append(f"const lv_img_dsc_t {VAR_NAME} = {{")
    lines.append(f"  .header.cf = LV_IMG_CF_TRUE_COLOR,")
    lines.append(f"  .header.always_zero = 0,")
    lines.append(f"  .header.reserved = 0,")
    lines.append(f"  .header.w = {w},")
    lines.append(f"  .header.h = {h},")
    lines.append(f"  .data_size = {len(raw)},")
    lines.append(f"  .data = {VAR_NAME}_map,")
    lines.append("};")
    lines.append("")

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated: {OUTPUT_FILE}")
    print(f"Data size: {len(raw)} bytes ({w*h} pixels * 2, no alpha)")

if __name__ == "__main__":
    main()
